### ISSUE TITLE
snk file not found

### ISSUE THREAD

**Issue by hishaks** [sergey-tihon/Stanford.NLP.NET#101]
I tried to build the project using the build script. But the resulting dll came out as unsigned as the snk file was not present in the location nuget\Stanford.NLP.snk.

**Comment by sergey-tihon** [comment]
yeap, this is by design.

You can [generate your own key](https://docs.microsoft.com/en-us/dotnet/standard/assembly/create-public-private-key-pair) if need signed assemblies

``` 
sn -k Stanford.NLP.snk
```

**Comment by hishaks** [comment]
After generating the .snk file, the build fails with the error joda-time.dll not found. It seems it's looking for the file in the root folder. I tried tweaking the script a little bit by supplying the correct path at:
                ModuleDefinition
                    .ReadModule(task.DllFile)
                    .Write(task.DllFile, WriterParameters(StrongNameKeyPair=key))
But it resulted in a compiler error. I am not well versed with F#.
Are you able to build by supplying the .snk file?

**Comment by sergey-tihon** [comment]
Yes, it should work on windows when you run `.\build.cmd NuGet`

<img width="1628" alt="image" src="https://user-images.githubusercontent.com/1197905/72594365-4225e700-3918-11ea-97c9-c7649f28af05.png">
