### ISSUE TITLE
Setup config

### ISSUE THREAD

**Issue by Rand0m-Guy** [sergey-tihon/Stanford.NLP.NET#104]
Hi!
I'm pretty new to software development but I require to use Stanford CoreNLP NET in Unity for a project I'm working on. I honestly don't know what to do...

I installed the CoreNLP NET package within Visual Studio using the NuGet package manager. I also placed the whole CoreNLP in the Assets Folder (don't even know if that's necessary or not).
However, in the package imports, "using edu.stanford.nlp.pipeline;" is marked as an error. I also tried using "using Stanford.NLP.CoreNLP", to no avail. (The Java version of the NLP is v4.0.0 while the NuGet NET version is v3.9.2, don't know if that makes a difference, although the Java one is not referenced in the Project, so it shouldn't)

I don't even know if I'm doing the right stuff to get it working (again, pretty new, especially to C# and Unity) and any type of feedback / direction is highly appreciated.

Thank you

**Comment by Rand0m-Guy** [comment]
Okay, managed to make it half-work but now I don't know how to use properties if java.util.Properties is not supported

**Comment by sergey-tihon** [comment]
What do you mean by `java.util.Properties` is not supported? It is inside IKVM Nuget package

**Comment by Rand0m-Guy** [comment]
Yeah sorry found out yesterday and forgot to close the thread... Thanks so much nonetheless!
