### ISSUE TITLE
POS-Tagging in other languages

### ISSUE THREAD

**Issue by Rand0m-Guy** [sergey-tihon/Stanford.NLP.NET#106]
While checking the documentation, I noticed that the .NET port of the POS tagger only supports a couple of languages. I need it for a non-supported language (spanish, specifically). What I have been trying for some weeks now is to use a dll version of the jar file of the language supplied by Stanford CoreNLP, however it does not seem to work.
When using
`var tagger = new MaxentTagger(@"C:/Users/myUser/Desktop/UnityProyect/Assets/Plugins/spanish-ud.tagger");`
It throws
```
IOException: Unable to open "C:/Users/myUser/Desktop/UnityProyect/Assets/Plugins/spanish-ud.tagger" as class path, filename or URL
edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem (System.String textFileOrUrl) (at <3882360035dc4dd4a6bff58e8ebe2d3f>:0)
edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit (java.util.Properties config, System.String modelFileOrUrl, System.Boolean printLoading) (at <3882360035dc4dd4a6bff58e8ebe2d3f>:0)
Rethrow as RuntimeIOException: Error while loading a tagger model (probably missing model file)
edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit (java.util.Properties config, System.String modelFileOrUrl, System.Boolean printLoading) (at <3882360035dc4dd4a6bff58e8ebe2d3f>:0)
edu.stanford.nlp.tagger.maxent.MaxentTagger..ctor (System.String modelFile, java.util.Properties config, System.Boolean printLoading) (at <3882360035dc4dd4a6bff58e8ebe2d3f>:0)
edu.stanford.nlp.tagger.maxent.MaxentTagger..ctor (System.String modelFile) (at <3882360035dc4dd4a6bff58e8ebe2d3f>:0)
Test.POS (System.String text) (at Assets/Scripts/Test.cs:69)
Test.Start () (at Assets/Scripts/Test.cs:34)
```

As a way of trying to experiment, also tried routing it to the original jar file, only for it to throw the same IOException. Also tried using "props.setProperty(...)" but, same error was thrown.

How should I use a Stanford CoreNLP language model with the .NET version?

**Comment by sergey-tihon** [comment]
1. What NuGet Package do you use? `Stanford.NLP.CoreNLP` or `Stanford.NLP.POSTagger`? (What version)
1. Do you have file `C:/Users/myUser/Desktop/UnityProyect/Assets/Plugins/spanish-ud.tagger`?
1. Where you downloaded this file from?
1. Plz share you code snippet

**Comment by Rand0m-Guy** [comment]
1.- I'm using Stanford.NLP.CoreNLP (3.9.2) downloaded from NuGet, which means in the Unity Assets Folder I'm referencing these Stanford dll's:
![image](https://user-images.githubusercontent.com/68619071/88692616-e3f66f80-d0c3-11ea-981e-fd0326b73486.png)

And these IKVM dll's:

![image](https://user-images.githubusercontent.com/68619071/88693080-7ac32c00-d0c4-11ea-9b80-2caa7e81129f.png)


2.- Technically speaking... no. (Lemme explain lol) that was the reference used when I used the original Stanford CoreNLP in Java. What I have is the Spanish model provided by Stanford. I tried referencing it directly (maybe I did it in a wrong way), and I also have it converted to a dll via IKVM

3.- NuGet

4.- Sure:


```
using System.Collections;
using System.Collections.Generic;
using edu.stanford.nlp.ling;
using edu.stanford.nlp.pipeline;
using edu.stanford.nlp.tagger.maxent;
using java.io;
using java.util;
using UnityEngine;
using System;
using System.IO;

public class Test : MonoBehaviour
{

    StanfordCoreNLP scnlp;
    Properties props;
    string propname = "tokenize, ssplit, pos, lemma, ner";

    void Start()
    {
        props = new Properties();
        props.setProperty("annotators", propname);

        scnlp = new StanfordCoreNLP(props);

        string text = "Hola, esto es un texto en español.";    //Spanish text
        POS(text);
    }

    void Update()
    {
        
    }

    public void POS(string text) {
        var tagger = new MaxentTagger(@"C:/Users/myUser/Desktop/UnityProyect/Assets/Plugins/spanish-ud.tagger");
        var sentences = MaxentTagger.tokenizeText(new java.io.StringReader(text)).toArray();
        foreach (java.util.ArrayList sentence in sentences)
        {
            var taggedSentence = tagger.tagSentence(sentence);
            Debug.Log(SentenceUtils.listToString(taggedSentence, false));
        }
    }
}
```

**Comment by sergey-tihon** [comment]
__Option 1__

If you want to use `var tagger = new MaxentTagger(@"C:/Users/myUser/Desktop/UnityProyect/Assets/Plugins/spanish-ud.tagger");` then you need file `C:/Users/myUser/Desktop/UnityProyect/Assets/Plugins/spanish-ud.tagger` physically available at this path. 

Just unzip Java `*.jar` with Spanish model and provide full path to `spanish-ud.tagger` file. Also in this flow you do not need lines

```csharp
        props = new Properties();
        props.setProperty("annotators", propname);

        scnlp = new StanfordCoreNLP(props);
```

because you do not use `scnlp`.

__Option 2__

You can go with `StanfordCoreNLP` and build annotators pipeline.

https://github.com/sergey-tihon/Stanford.NLP.NET/blob/v4/tests/Stanford.NLP.CoreNLP.Tests/CoreNlpTests.cs#L73-L93

then process your `text` and receive `Annonation` with all metadata extracted by annotators from your pipeline

https://github.com/sergey-tihon/Stanford.NLP.NET/blob/v4/tests/Stanford.NLP.CoreNLP.Tests/CoreNlpTests.cs#L95-L97

here is an example of how you can manually extract data from different kinds of annotations

https://github.com/sergey-tihon/Stanford.NLP.NET/blob/v4/tests/Stanford.NLP.CoreNLP.Tests/CoreNlpTests.cs#L106-L151

**Comment by Rand0m-Guy** [comment]
You are honestly the best. Thank you so so much!
