### ISSUE TITLE
The new .NET Core merge works except very minor issues

### ISSUE THREAD

**Issue by GeorgeS2019** [sergey-tihon/Stanford.NLP.NET#121]
The UNPACKING did not work for TWO folders
- data\paket-files\nlp.stanford.edu\stanford-parser-full-2020-11-17
- data\paket-files\nlp.stanford.edu\stanford-corenlp-4.5.0
![image](https://user-images.githubusercontent.com/49812372/186632609-309614bc-7a1c-4811-b08a-aaa74f56d259.png)

**Comment by sergey-tihon** [comment]
It works, but not when you `build from VS`

Run `.\build.cmd -t RunTests` this command download model and unpack them before tests execution
https://github.com/sergey-tihon/Stanford.NLP.NET/blob/master/build.fsx#L370-L377

After that everything will be fine in VS.
