### ISSUE TITLE
Feedback Additional Standford.NLP Tools: PyTorch Dependency Parser

### ISSUE THREAD

**Issue by GeorgeS2019** [sergey-tihon/Stanford.NLP.NET#122]
This is MORE of a feedback.

[Additional Tools: PyTorch Dependency Parser](https://stanfordnlp.github.io/CoreNLP/pytorch-depparse.html)

>The purpose of this library is to train models for the Java code base
### Relationship with [stanza](https://github.com/stanfordnlp/stanza): Which is a full-featured Python dependency parser.

I look through [PyTorch Dependency Parser](https://github.com/stanfordnlp/nn-depparser), if there is interest,  this can be ported to .NET using [**TorchSharp**](https://github.com/dotnet/TorchSharp)!

The **TorchAudio (.NET)** part of TorchSharp is progressing well, for users interested of TTS and STT.
The **TorchText (.NET)** (Deep NLP) part could potentially benefit from this community which @sergey-tihon developed over MANY Years

**Comment by sergey-tihon** [comment]
@GeorgeS2019 You implemented it or closed because of no-reply? ☺️
