### ISSUE TITLE
CoreNLP Server

### ISSUE THREAD

**Issue by GeorgeS2019** [sergey-tihon/Stanford.NLP.NET#125]
https://stanfordnlp.github.io/CoreNLP/corenlp-server.html#getting-started

Could the current .NET Core version provides CoreNLP server or it needs to be ported over to .NET Core using the latest IKVM?

FYI: [.NET client ](https://github.com/AMArostegui/CoreNLPClient.Net)to CoreNLP server

**Comment by sergey-tihon** [comment]
I do not see much value in running Sever on top of IKVM. You can just start it as Java process and have native performance.

It was possible to use this library as a client for CoreNLP Server (but I have not tried with .NET Core)
http://sergey-tihon.github.io/Stanford.NLP.NET/#/corenlp/Server

**Comment by GeorgeS2019** [comment]
@sergey-tihon  

It fails here
https://github.com/sergey-tihon/Stanford.NLP.NET/blob/eefbfb549f138258d161c2184b80f57d003df035/tests/Stanford.NLP.CoreNLP.Tests/StanfordServer.cs#L40

The returned sentences was null

**Comment by GeorgeS2019** [comment]
I could get [CoreNLPClient.Net](https://github.com/AMArostegui/CoreNLPClient.Net) .NET reimplementation of the Stanza client - working

**Comment by GeorgeS2019** [comment]
> It was possible to use this library as a client for CoreNLP Server (but I have not tried with .NET Core)
http://sergey-tihon.github.io/Stanford.NLP.NET/#/corenlp/Server

I think the code generally works but must feed a minimum of 2 sentences. Not one;.)

**Comment by GeorgeS2019** [comment]
With the way I set up the CoreNLP server, simply unzip the stanford-corenlp-4.5.0.zip
This works
props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner");

But not when additional "parse, dcoref" are added
https://github.com/sergey-tihon/Stanford.NLP.NET/blob/eefbfb549f138258d161c2184b80f57d003df035/tests/Stanford.NLP.CoreNLP.Tests/StanfordServer.cs#L23

**Comment by GeorgeS2019** [comment]
This is well [addressed ](https://github.com/sergey-tihon/Stanford.NLP.NET/pull/130#issuecomment-1971462738)now with 4.6.0
