### ISSUE TITLE
Signed version for stanford.nlp.PosTagger

### ISSUE THREAD

**Issue by vineet-singh26** [sergey-tihon/Stanford.NLP.NET#127]
can you please make the latest version signed in?

**Comment by sergey-tihon** [comment]
First of all you most likely need to use -  Stanford.NLP.CoreNLP.

Second question, why do you need signature these days?

**Comment by vineet-shekhawat** [comment]
I am using Stanford.NLP.PosTagger for fetching tags for a query.
I am integrating it in my project, where we can't integrate packages which are not signed.
Can you please help with that?

**Comment by vineet-singh26** [comment]
I am using Stanford.NLP.PosTagger for fetching tags for a query.
I am integrating it in my project, where we can't integrate packages which are not signed.
Can you please help with that?

Thankyou
