### ISSUE TITLE
Upgrade 4.5.5?

### ISSUE THREAD

**Issue by GeorgeS2019** [sergey-tihon/Stanford.NLP.NET#128]
@sergey-tihon 
Just wonder with the latest IKVM for .NET6, will the process of upgrading become simpler?

**Comment by sergey-tihon** [comment]
Why it should be simpler? Have you tried to use MavenReference directly with CoreNlp?

**Comment by GeorgeS2019** [comment]
U are right..I cannot be sure. U have written complex automated scripts.

If the ikvm team is doing right..your job should be simpler.

**Comment by GeorgeS2019** [comment]
https://github.com/yakivyusin/SimpleNetNlp/issues/23#issuecomment-1837149332

**Comment by GeorgeS2019** [comment]
This is solved now with 4.6.0
https://github.com/sergey-tihon/Stanford.NLP.NET/pull/130#issuecomment-1971462738
