### ISSUE TITLE
Request for C# sample to extract word, pos, ne etc from CoreMap

### ISSUE THREAD

**Issue by pchankh** [sergey-tihon/Stanford.NLP.NET#13]
Hi Sergey,

Thanks for your great effort in porting to .Net.  We are scratching our heads on porting the following code to .Net. (especially the CoreMap sentence , word, pos, and ne portion).  Will be great if you can include and expand your StanfordCoreNLP C# sample.  Much Appreciated.

Patrick

http://sergey-tihon.github.io/Stanford.NLP.NET/StanfordCoreNLP.html

Request for help to expand the sample C# to include the parsing for POS, Word, and NE, Normalized Entity etc as in 

 // creates a StanfordCoreNLP object, with POS tagging, lemmatization, NER, parsing, and coreference resolution 
    Properties props = new Properties();
    props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, parse, dcoref");
    StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
    
    // read some text in the text variable
    String text = ... // Add your text here!
    
    // create an empty Annotation just with the given text
    Annotation document = new Annotation(text);
    
    // run all Annotators on this text
    pipeline.annotate(document);
    
    // these are all the sentences in this document
    // a CoreMap is essentially a Map that uses class objects as keys and has values with custom types
    List<CoreMap> sentences = document.get(SentencesAnnotation.class);
    
    for(CoreMap sentence: sentences) {
      // traversing the words in the current sentence
      // a CoreLabel is a CoreMap with additional token-specific methods
      for (CoreLabel token: sentence.get(TokensAnnotation.class)) {
        // this is the text of the token
        String word = token.get(TextAnnotation.class);
        // this is the POS tag of the token
        String pos = token.get(PartOfSpeechAnnotation.class);
        // this is the NER label of the token
        String ne = token.get(NamedEntityTagAnnotation.class);       
      }

      // this is the parse tree of the current sentence
      Tree tree = sentence.get(TreeAnnotation.class);

      // this is the Stanford dependency graph of the current sentence
      SemanticGraph dependencies = sentence.get(CollapsedCCProcessedDependenciesAnnotation.class);
    }

    // This is the coreference link graph
    // Each chain stores a set of mentions that link to each other,
    // along with a method for getting the most representative mention
    // Both sentence and token offsets start at 1!
    Map<Integer, CorefChain> graph = 
      document.get(CorefChainAnnotation.class);

**Comment by sergey-tihon** [comment]
@volhav Could you help here?

**Comment by volhav** [comment]
@sergey-tihon I'm a little bit out of time for the moment, but hopefully will be able to look at it soon. In case you or anybody else not finish it till then:)

**Comment by sergey-tihon** [comment]
Oh... I already did port of this `Java` code to `F#` tests.
See here https://github.com/sergey-tihon/Stanford.NLP.NET/blob/master/tests/Stanford.NLP.CoreNLP.FSharp.Tests/CoreNLP.fs#L14-L52

**Comment by volhav** [comment]
@sergey-tihon I knew it!)
@pchankh let me know if you need help in porting it from F# to C#

**Comment by pchankh** [comment]
Hi Sergey,

Thanks so much for providing the F# code. As my team is working using C#, appreciate if your team can help.

Cheers
Dr Patrick

**Comment by sergey-tihon** [comment]
@volhav Could you convert code to C# and add to https://github.com/sergey-tihon/Stanford.NLP.NET/tree/master/samples/Stanford.NLP.Parser.CSharp ?

**Comment by volhav** [comment]
@sergey-tihon Sure, I'll try to)

**Comment by sergey-tihon** [comment]
Hi @volhav , any update for this?

**Comment by volhav** [comment]
Hi, I am overload with my work project now, so didn't have a chance for
code conversion, sorry for this

2015-04-23 10:47 GMT+03:00 Sergey Tihon <notifications@github.com>:

**Comment by pchankh** [comment]
Dear Sergey,

We have converted the code and will post for your team reference shortly.
Thanks

Dr Patrick

**Comment by pchankh** [comment]
Hi Sergey,

As promised, here is our code from your F# convert:
sentences = annotation.get(new
CoreAnnotations.SentencesAnnotation().getClass()) as ArrayList;
foreach (CoreMap sentence in sentences)
{
 var tokens = sentence.get(new
CoreAnnotations.TokensAnnotation().getClass()) as ArrayList;
 foreach(CoreLabel token in tokens)
 {

  var word = token.get(new CoreAnnotations.TextAnnotation().getClass());
  var pos = token.get(new
CoreAnnotations.PartOfSpeechAnnotation().getClass());
  var ner = token.get(new
CoreAnnotations.NamedEntityTagAnnotation().getClass());
  var normalizedner = token.get(new
CoreAnnotations.NormalizedNamedEntityTagAnnotation().getClass());
  var time = token.get(new TimeExpression.Annotation().getClass()) as
TimeExpression;
  Console.WriteLine("{0} \t[pos={1}; \tner={2}; \tnormner={3}", word, pos,
ner,normalizedner);
 }
}
Thanks
Dr Patrick Chan

**Comment by sergey-tihon** [comment]
Thank you @pchankh !
