### ISSUE TITLE
Request to have C# samples 

### ISSUE THREAD

**Issue by pchankh** [sergey-tihon/Stanford.NLP.NET#14]
Hi Sergey,

Will be great if you can also have a counterpart C# samples alongside F#.
Much appreciated.

Cheers
Patrick

**Comment by sergey-tihon** [comment]
Each site page contains a C# sample at the very bottom. This is not enough?
http://sergey-tihon.github.io/Stanford.NLP.NET/StanfordCoreNLP.html

**Comment by JamesWHurst** [comment]
I have not seen one yet that actually works though.

**Comment by sergey-tihon** [comment]
You do not need Java at all. Everything that you need is in NuGet packages.
Could you try [sample from this repo](https://github.com/sergey-tihon/Stanford.NLP.NET/blob/master/samples/Stanford.NLP.Parser.CSharp/Program.cs)? 
Or download this repo and execute `build All`?

**Comment by sergey-tihon** [comment]
I will be glad to improve docs, but I think that do not understand errors and inconsistencies that you have. From my point of view everything is simple:

1) Reference NuGet package
2) Download pre-trained model
3) Copy-parse sample from the site
4) Compile and execute

Could you help me understand which step is more problematic and help to improve it?

**Comment by Davtomas** [comment]
this issue should be closed
