### ISSUE TITLE
Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl

### ISSUE THREAD

**Issue by TheTurducken** [sergey-tihon/Stanford.NLP.NET#19]
Hello, I am  trying to run through your example code, and I ran into this error:
An unhandled exception of type 'edu.stanford.nlp.util.ReflectionLoading.ReflectionLoadingException' occurred in stanford-corenlp-3.5.2.dll
Additional information: Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl

I copied your example exactly, and I am using 3.5.2. What could I be doing wrong?

**Comment by sergey-tihon** [comment]
Please try to set `ner.useSUTime` [to 0](https://github.com/sergey-tihon/Stanford.NLP.NET/blob/master/tests/Stanford.NLP.CoreNLP.FSharp.Tests/CoreNLP.fs#L61) or [to false](https://github.com/sergey-tihon/Stanford.NLP.NET/blob/master/tests/Stanford.NLP.CoreNLP.FSharp.Tests/CoreNLP.fs#L93)
