### ISSUE TITLE
An unhandled exception of type 'System.TypeInitializationException' occurred

### ISSUE THREAD

**Issue by crack521** [sergey-tihon/Stanford.NLP.NET#23]
Hello, I am trying to run through your example code, and I ran into this error:
An unhandled exception of type 'System.TypeInitializationException' occurred in stanford-corenlp-3.5.2.dll
Additional information: The type initializer for 'edu.stanford.nlp.util.Timing' threw an exception
I copied your example exactly, and I am using 3.5.2. What could I be doing wrong?

**Comment by sergey-tihon** [comment]
Please try to turn of SUTime
```fsharp
props.setProperty("ner.useSUTime", "false") |> ignore
```

**Comment by crack521** [comment]
I changed the value of props as you suggested,but this error occurred again,What could I be doing wrong?

**Comment by sergey-tihon** [comment]
Could you pleas paste your source code here? (I was able to run it)

**Comment by crack521** [comment]
java.util.Properties props = new java.util.Properties();
            var jarRoot = @"E:\codehub\java\stanford-corenlp-full-2015-04-20\stanford-corenlp-full-2015-04-20\stanford-corenlp-3.5.2-models\";
            var modelsDirectory = jarRoot + @"\edu\stanford\nlp\models";
            props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, parse, dcoref");
            props.setProperty("ner.useSUTime", "0");
            var curDir = Environment.CurrentDirectory;
            Directory.SetCurrentDirectory(jarRoot);
            StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
            Directory.SetCurrentDirectory(curDir);
            String text = "Dan Ramage is working for\nMicrosoft. He's in Seattle! \n";
            Annotation document = new Annotation(text);
            pipeline.annotate(document);
            var sentences = document.get(typeof(CoreAnnotations.SentencesAnnotation));

**Comment by crack521** [comment]
When the program runs,it occurs errors in the line of
"  StanfordCoreNLP pipeline = new StanfordCoreNLP(props);" 
An unhandled exception of type 'System.TypeInitializationException' occurred in stanford-corenlp-3.5.2.dll Additional information: The type initializer for 'edu.stanford.nlp.util.Timing' threw an exception

**Comment by toncho11** [comment]
Change the culture in .NET to "US".

```python
    CultureInfo ci = new CultureInfo("en-US");
    Thread.CurrentThread.CurrentCulture = ci;
    Thread.CurrentThread.CurrentUICulture = ci;
    
    tagger = new MaxentTagger(modelsDirectory + @"\french.tagger");
```
I had the same problem. On 2 computers it works fine and on 2 other it does not. So I figured it was something in the environment related to time, so I changed the culture. I am working with the POS tagger for French text.

**Comment by crack521** [comment]
@toncho11  Thanks a lot!

**Comment by sergey-tihon** [comment]
@toncho11 Thank you for help.
@crack521 Please close this issue if the it is resolved
