### ISSUE TITLE
Scores for tagged NER results?

### ISSUE THREAD

**Issue by adeperio** [sergey-tihon/Stanford.NLP.NET#26]
Hi Sergey, 

Great work on this port by the way! 

I'm using the Sandford CoreNLP.NET module and its CRFClassifier to find Named Entities in a document. I am able to get the entities by using classifyWithInlineXML, but would you know how to get the entities along with their relevance/confidence scores (0-1)?

Would love an example in C# on how to do this.

**Comment by sergey-tihon** [comment]
You asked this question on SO 
http://stackoverflow.com/questions/32796011/scores-for-tagged-ner-results-in-the-standfordcore-nlp-net-library (I posted my suggestion there)

Maybe @volhav may help with C# sample?

**Comment by siddhupiddu** [comment]
Can you share a c# sample? I am having problems with emulating the java code to c#

**Comment by sergey-tihon** [comment]
Close as an old issue
