### ISSUE TITLE
Stanford.NLP.NET/StanfordWordSegmenter.html cSharp fails

### ISSUE THREAD

**Issue by Davtomas** [sergey-tihon/Stanford.NLP.NET#30]
https://sergey-tihon.github.io/Stanford.NLP.NET/StanfordWordSegmenter.html

I create a console project, use nuget to install the segmentation library. I hope this naturally install all other relevant dependent ikvm library.

Copy and past the code and modify to include the right model and test file directoriy

The program fails ONLY AT THIS STEP:
segmenter.loadClassifierNoExceptions(segmenterData + @"ctb.gz", props); 

outout: The thread 0x262c has exited with code 0 (0x0).

Could someone repeat to let me know if there is something I miss

**Comment by Davtomas** [comment]
The model directory ends with    \stanford-segmenter-2015-04-20\data\";

**Comment by sergey-tihon** [comment]
Plz try to add these 3 lines 
https://github.com/sergey-tihon/Stanford.NLP.NET/blob/master/tests/Stanford.NLP.Segmenter.FSharp.Tests/Segmenter.fs#L23-L25
// cc @volhav

**Comment by sergey-tihon** [comment]
hmm, no - you do not need these lines.
After small changes in sample from docs https://github.com/sergey-tihon/Stanford.NLP.NET/commit/dbe091b671cc677874675dd7a68dc22dc9eaab45
it should work like this
![segmenter](https://cloud.githubusercontent.com/assets/1197905/10352211/677ce798-6d56-11e5-9b4c-b5bfc81e3dcd.gif)

**Comment by Davtomas** [comment]
I need c# sample to work. Please kindly check. So far, most of my problem involving ikvm converted jar to dll hangs will loading large size of model. any advice?

**Comment by Davtomas** [comment]
The c# sample provide this on output window
The thread 0x35e8 has exited with code 259 (0x103).
The thread 0x1808 has exited with code 259 (0x103).
The thread 0x2d4c has exited with code 259 (0x103).
The thread 0x3d74 has exited with code 0 (0x0).

For more information to people debuging ikvm ported program
http://stackoverflow.com/questions/18887864/what-is-a-thread-exit-code

**Comment by Davtomas** [comment]
Finally, I get the output. Problem, it takes not 20+ seconds like in running java, but 15+ minutes. Not sure why. Second, the output is in wrong encoding. 
闈㈠ 鏂?涓栫邯 锛?涓栫晫 鍚?鍥?浜烘皯 鐨?鍏卞悓 鎰挎湜 鏄?锛?缁х画 鍙戝睍 浜虹被 浠ュ線 鍒涢€?鐨?涓€鍒?鏂囨槑 鎴愭灉 锛?鍏嬫湇 20 涓栫邯 鍥版壈 鐫€ 浜虹被 鐨?鎴樹簤 鍜?璐洶 闂 锛?鎺ㄨ繘 鍜屽钩 涓?鍙戝睍 鐨?宕囬珮 浜嬩笟 锛?鍒涢€?涓€ 涓?缇庡ソ 鐨?涓栫晫 銆?

Perhaps, there is something wrong with loading the model file due to my window 8 setting in dealing with Chinese encoding.

**Comment by sergey-tihon** [comment]
x32 ок x64 ? Could you try to build you app in Release mode for x32 arch?

**Comment by Davtomas** [comment]
could you send me a simple console zip file of compiled c# segmentation sample for me to diagnose what is wrong with my windows 8 visual studio 2013 issues ?

**Comment by Davtomas** [comment]
I have compiled x64 release, it has been more than 10+ minutes, I am still waiting for the output

**Comment by sergey-tihon** [comment]
would be interesting to compare it with the same code compiled for x32

**Comment by Davtomas** [comment]
Not sure I understand your rationale for doing so. I have started to move to java, abandoning .NET for stanfordNLP as I could not figure out the problem. Thanks for your help

**Comment by Davtomas** [comment]
May be this could help others learning Stanfordnlp:NET - contributed by you
https://visualstudiogallery.msdn.microsoft.com/540ac2d8-f881-4794-8b00-810d28257b70

**Comment by Davtomas** [comment]
I solved my problems. 

I changed the testfile to avoid this. It has to do with my Windows 8 settings. Using new Chinese textfile or textstring defined in the code, I get the expected results.

Below only happens to the provided testfile. Have not figure out why yet.

闈㈠ 鏂?涓栫邯 锛?涓栫晫 鍚?鍥?浜烘皯 鐨?鍏卞悓 鎰挎湜 鏄?锛?缁х画 鍙戝睍 浜虹被 浠ュ線 鍒涢€?鐨?涓€鍒?鏂囨槑 鎴愭灉 锛?鍏嬫湇 20 涓栫邯 鍥版壈 鐫€ 浜虹被 鐨?鎴樹簤 鍜?璐洶 闂 锛?鎺ㄨ繘 鍜屽钩 涓?鍙戝睍 鐨?宕囬珮 浜嬩笟 锛?鍒涢€?涓€ 涓?缇庡ソ 鐨?涓栫晫 銆?
