### ISSUE TITLE
CoreNLP c# sample fails on 'ner' load

### ISSUE THREAD

**Issue by volhav** [sergey-tihon/Stanford.NLP.NET#32]
I faced the following issue with old CoreNLP c# sample:

```fsharp
line 22: props.setProperty("annotators", "tokenize, ssplit, pos, lemma, parse, ner, dcoref"); 
```

fails on loading 'ner'. I have removed ner and dependent dcoref and sample worked fine. 

Could you please check what is wrong with 'ner' or it was my environment issue? (New c# sample contains my comment about this issue and needed to be reverted if it's local problem)

**Comment by Davtomas** [comment]
I persevere learning StanfordNLP.net. Finally it pays off. 
I have tested the latest c# sample code on CoreNLP. It works.  Thanks sergey for timely support.

**Comment by Davtomas** [comment]
https://github.com/sergey-tihon/Stanford.NLP.NET/blob/master/samples/Stanford.NLP.CoreNLP.CSharp/Program.cs


//ner fails -> dcoref depends on ner

this issues has been discussed before in one of the closed issues. This has to be included.
props.setProperty("ner.useSUTime", "false");

**Comment by volhav** [comment]
Thanks @Davtomas. I have updated the sample to avoid confusion
