### ISSUE TITLE
new ideas for c# samples

### ISSUE THREAD

**Issue by JimSEOW** [sergey-tihon/Stanford.NLP.NET#34]
https://medium.com/@klintcho/training-a-swedish-pos-tagger-for-stanford-corenlp-546e954a8ee7

**Comment by sergey-tihon** [comment]
@Davtomas Do you want to create PR with C# sample for this?)

**Comment by Davtomas** [comment]
The stanfordnlp.NET you started is a good platform for others to share
http://stackoverflow.com/questions/15609324/training-n-gram-ner-with-stanford-nlp

**Comment by sdg002** [comment]
Very useful. Thank you for doing this work.

**Comment by sdg002** [comment]
Subject: POS results of C# different from the online version

Hi All,
I tried parsing the following sentence using the online page hosted here(http://nlp.stanford.edu:8080/parser/index.jsp).
and compared the with the results I get from my custom application.

**Test string:**
The Vendor must not resell,sell, rent, lease, loan, supply, distribute, redistribute, publish or re-publish the Software.

**Results form online:**
not/RB resell/VB ,/, sell/VB ,/, rent/VB ,/, lease/VB ,/, loan/NN ,/, supply/VB

**Results from custom C# app using "wsj-0-18-bidirectional-nodistsim.tagger":**
not/RB resell/VB ,/, sell/VB ,/, rent/NN ,/, lease/NN ,/, loan/NN ,/, supply/NN

Notice that in the latter, the words **rent**, **lease** and **loan** have been classified as a **noun**. The online version has correctly classified as **verb**.
Please advice if I have missed something.

Thanks,
Sdg

**Comment by sergey-tihon** [comment]
@sdg002 Comare versions

Latest version on NuGet is 3.7.0 published at `2016-10-31`
Site still use
```
Parser: englishPCFG.ser.gz 
Last updated 2016-09-12
```

It may be difference in versions or in loaded parser (models)

**Comment by sergey-tihon** [comment]
Results from http://nlp.stanford.edu:8080/corenlp/process
![screen shot 2017-02-16 at 2 58 18 pm](https://cloud.githubusercontent.com/assets/1197905/23020494/6ba8df7c-f458-11e6-94e4-2f23bd98ccc0.png)

Results from http://corenlp.run
![screen shot 2017-02-16 at 2 59 00 pm](https://cloud.githubusercontent.com/assets/1197905/23020507/7c41f0ee-f458-11e6-9f20-3b32e2c0fe9a.png)

**Comment by sdg002** [comment]
thanks for looking into this so quickly.

**Comment by sergey-tihon** [comment]
Close as an old issue
