### ISSUE TITLE
How to get only the tags of the POS Tagger?

### ISSUE THREAD

**Issue by falkindustries** [sergey-tihon/Stanford.NLP.NET#35]
Hello sergey-tihon,

really good work! I managed to get the example in c# (VS2015) to work. Now i want to get only the tags of the POS Tagger. 
var text = "Ich. Du. Machen. Legen. Hans. Peter.";
normal output with Console.WriteLine(Sentence.listToString(taggedSentence, false))
"Ich/PPER ./$. Du/PPER ./&. Machen/VVINF ./$. Legen/VVINF ./$. Hans/NE ./$. Peter/NE ./$"

with Console.WriteLine(Sentence.listToString(taggedSentence, true)) i get only the input sentence without the tags. I need only the tags, sort it and analyse the text with some metriks.

Thank you for your help!!!

**Comment by sergey-tihon** [comment]
You can analyze your parse tree (`Tree` object) recursively 
`.label()` - returns label of the current node
`.isLeaf()` - returns `true`/`false` if it is leaf or not
`.getChildrenAsList()` - returns children nodes
Here you can find [my F# sample](http://sergey-tihon.github.io/Stanford.NLP.Fsharp/so_questions.html)

Just [DFS](https://en.wikipedia.org/wiki/Depth-first_search) the tree and print whatever you need.

**Comment by falkindustries** [comment]
Thank you for your fast reply!. I checked the links and tried your parser code example in c#.
I thought there would be a list which contains only the tags or something like that. 
Now i think its easier to search in tagged sentences for the wanted tag (eg. "VMPP") and extract/count them for further analyse -> Problem solved.

Thank for your help!
