### ISSUE TITLE
Error parsing on Mono

### ISSUE THREAD

**Issue by mavnn** [sergey-tihon/Stanford.NLP.NET#37]
On trying to setup a pipeline for sentiment analysis on mono, mono crashes during the parsing phase.

Full repro and stack trace available at https://github.com/mavnn/Advent2015-trial; you should be able to clone that repository and reproduce. The stacktrace starts with:

```
Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... Assertion failed: (0), function amd64_patch, file mini-amd64.c, line 482.
Stacktrace:

  at <unknown> <0xffffffff>
  at java.util.HashMap.putVal (int,object,object,bool,bool) <0x00209>
  at java.util.HashMap.put (object,object) <0x0004a>
  at edu.stanford.nlp.parser.lexparser.BinaryGrammar.readObject (java.io.ObjectInputStream) <0x00171>
  at (wrapper dynamic-method) edu.stanford.nlp.parser.lexparser.BinaryGrammar.__<Invoker> (object,object[],ikvm.internal.CallerID) <0x00177>
  at Java_sun_reflect_ReflectionFactory/FastMethodAccessorImpl.invoke (object,object[],ikvm.internal.CallerID) <0x0003d>
  at java.lang.reflect.Method.invoke (object,object[],ikvm.internal.CallerID) <0x000d4>
...
```

This is the first time I've used Stanford NLP, so it is entirely possible that I'm at fault here.

**Comment by sergey-tihon** [comment]
@mavnn not related to your issue, but paket can restore all model for you and unzip them without `bootstrap.fsx` 
See here https://github.com/sergey-tihon/Stanford.NLP.NET/blob/master/paket.dependencies

**Comment by sergey-tihon** [comment]
Everything work nicely on Windows =(

But, could you please try to comment two files
```fsharp
#I "packages/Stanford.NLP.Parser/lib/"
#r "stanford-parser.dll"
```
my [Stanford.NLP.NET landing page](http://sergey-tihon.github.io/Stanford.NLP.NET/) says that

> Note: Do not try to reference several NuGet packages from your solution. They are incompatible with each other. If you need more than one - you should reference Stanford CoreNLP package. All features are packed inside.

`CoreNLP` package is super-set of all Stanford packages, so reflection on `Mono` may be confused when find same types in different assemblies.

**Comment by mavnn** [comment]
I changed to using the paket file dependencies (thanks, hadn't realised about the unzipping) but that doesn't seem to unzip the jar of the models.

I now seem to have two problems: if I run the full example I get

```
Adding annotator tokenize
TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
Adding annotator ssplit
Adding annotator pos
java.lang.RuntimeException: edu.stanford.nlp.io.RuntimeIOException: Unrecoverable error while loading a tagger model
Stopped due to error
```
If I remove "pos" from the pipeline for testing, I get:

```
Adding annotator tokenize
TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
Adding annotator ssplit
Adding annotator parse
Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Unable to resolve "edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz" as either class path, filename or URL
Stopped due to error
```
If I unzip the jar file with the models I get back to the old stack trace.

Looks like there's something different about how IKVM is behaving on mono (or osx) vs. .net (or windows) when it comes to discovering locations of things. And possible other issues as well :D

**Comment by sergey-tihon** [comment]
Close this as an old issue, should be fine with .NET Core binaries
