### ISSUE TITLE
sutime sample code throws exceptions

### ISSUE THREAD

**Issue by siddhupiddu** [sergey-tihon/Stanford.NLP.NET#41]
I am getting the following exception while running the sutime sample code. I have included all the dlls. Do you have any suggestions?

An exception of type 'System.TypeInitializationException' occurred in stanford-corenlp-3.6.0.dll but was not handled in user code

Additional information: The type initializer for 'edu.stanford.nlp.time.XMLUtils' threw an exception.

**Comment by siddhupiddu** [comment]
More detail. The innerexception in the typeinitializationexception is:

{javax.xml.transform.TransformerFactoryConfigurationError: Provider com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl not found}

I have installed the corenlp nugget and I believe all the IKVm java dlls are there

**Comment by sergey-tihon** [comment]
@siddhupiddu Hi, could you please post the solution for this issue?

**Comment by siddhupiddu** [comment]
Hi Sergey,
The problem was with the IKVM. I had not correctly installed IKVM.
Reinstalling the nugget package fixed it.

Thanks!
