### ISSUE TITLE
dependency parser problem in asp.net app 

### ISSUE THREAD

**Issue by mehmetilker** [sergey-tihon/Stanford.NLP.NET#43]
Everthing works fine with all annotators in console application but I got this exception when I try on asp.net mvc.
If I remove depparse  it works. So the problem is depparse on asp.net or it is same for parse annotator too.

Is there any setting I need to change ?

![image](https://cloud.githubusercontent.com/assets/279289/13381264/81b35fcc-de60-11e5-8159-1a86ce3fb328.png)

The code is as follows:

`

var jarRoot = @"D:\Projects\nlp\stanford-corenlp-full-2015-12-09\stanford-corenlp-3.6.0-models";

            var text = "For the month of January, I've resolved to attempt to wean myself off sugar's toxic allure.";

            var props = new Properties();
            props.setProperty("annotators", "tokenize, ssplit, pos, lemma, depparse"); //not working : coref, mention
            //props.setProperty("annotators", "tokenize, ssplit, pos, depparse, lemma, ner, parse, dcoref"); //not working : coref, mention
            props.setProperty("ner.useSUTime", "0");

            // We should change current directory, so StanfordCoreNLP could find all the model files automatically
            var curDir = Environment.CurrentDirectory;
            Directory.SetCurrentDirectory(jarRoot);
            var pipeline = new StanfordCoreNLP(props);
            Directory.SetCurrentDirectory(curDir);

            System.Console.WriteLine("Setting configuration complated");

            // Annotation
            var document = new Annotation(text);
            pipeline.annotate(document);`

**Comment by sergey-tihon** [comment]
__Option 1__ Try IIS (not IIS express) - https://github.com/sergey-tihon/Stanford.NLP.NET/issues/15#issuecomment-77526331

__Option 2__ Try to increase stack size - https://github.com/sergey-tihon/Stanford.NLP.NET/issues/16#issuecomment-164655567

**Comment by mehmetilker** [comment]
Thank you for your quick reply.
I could not try on my local but it worked on Azure. 
So it is a problem related with IIS Express I assume.

I would like to add another observation.
When I comment out this line:
`pipeline.annotate(document);`
and add this part (from another issue thread)

`string result = "";
            using (java.io.StringWriter writer = new java.io.StringWriter())
            {
                pipeline.jsonPrint(document, writer);
                result = writer.toString();
            }`

It does not throw an exception but give empty result as follows.

{
}

**Comment by mehmetilker** [comment]
I would like to add some observations..

As I see leaving IIS express is some cumbersome just for this problem I tried to increase stack size with utilizing Thread class  but unfortunately it is not possible to handle return value in asp.net project.
Other option is Task.Run but there is no way to set maxStackSize...



`  new System.Threading.Thread(() =>
            {

            ......

                pipeline.annotate(document);
           ......
            }, 414565).Start();`

**Comment by mehmetilker** [comment]
For those who is wondering a simple solution:

By default II express is working in 32 bit mode.
And according to this article https://support.microsoft.com/en-us/kb/932909
" In Windows Server 2008 and higher, the maximum stack size of a thread running on 32-bit version of IIS is 256 KB, and on an x64 server is 512 KB."
All we need is little bit higher then 400K for depparse annotator.

So we can set 64bit version of IIS Express in VS 2015 Tools> Options> Projects and Solutions > Web Projects > Use the 64 bit version of IIS Express for web sites and projects

happy coding...

**Comment by sergey-tihon** [comment]
Thank you @mehmetilker !

**Comment by mehmetilker** [comment]
You are welcome @sergey-tihon. Thank you for your effort.
