### ISSUE TITLE
An unhandled exception of type 'System.StackOverflowException' occurred in IKVM.OpenJDK.Core.dll

### ISSUE THREAD

**Issue by hendyharf** [sergey-tihon/Stanford.NLP.NET#47]
I've got an error `An unhandled exception of type 'System.StackOverflowException' occurred in IKVM.OpenJDK.Core.dll` with this line code:
**pipeline.annotate(annotation);**

It works fine when I compile Stanford CoreNLP with ConsoleApp, but it's getting serious problem when I integrate it with WebApp. I'm using Visual Studio 2013. I've already marked up the Options -> Project and Solution -> Web Projects -> Use 64bit.. but it also does the same thing.

Any Ideas what's wrong with it? I use your code of Stanford CoreNLP.

```
        `var props = new Properties();
        props.setProperty("annotators", "tokenize, ssplit, parse");
        props.setProperty("ner.useSUTime", "false");

        // We should change current directory, so StanfordCoreNLP could find all the model files automatically
        var curDir = Environment.CurrentDirectory;
        Directory.SetCurrentDirectory(jarRoot);
        var pipeline = new StanfordCoreNLP(props);
        Directory.SetCurrentDirectory(curDir);

        // Annotation
        var annotation = new Annotation(text);
        pipeline.annotate(annotation);`
```

Is it something because of IIS? I don't use any separate IIS, I'm using IIS Express. Then tell me how to fix this problem with separated IIS. Or are there any other solutions?

Thank you,
Hendy Harf

**Comment by sergey-tihon** [comment]
What about 64bit version of IIS Express?
https://github.com/sergey-tihon/Stanford.NLP.NET/issues/46#issuecomment-217800803

**Comment by hendyharf** [comment]
I'm not sure how to do that. Any references? Is it something like this?

           new System.Threading.Thread(() =>
            {

            ......

                pipeline.annotate(document);
           ......
            }, 414565).Start();

Do I have to write my own code under `pipeline.annotate(document);` until close the brackets of the Thread? Or the thread code only until `pipeline.annotate(document);`?

**Comment by mehmetilker** [comment]
@hendyharf can you try without parse annotator ? If you are getting same error your problem can be something other then stack size problem.

If it works then check that your IIS Express is really working in 64bit mode. If your OS is 64 bit, alternatively you can try IIS (as a core windows service)...

**Comment by hendyharf** [comment]
@mehmetilker I've just tried to parse it without annotator

`props.setProperty("", "tokenize, ssplit, parse");`

It took for ages, like 15 minutes for me parse without annotator and it also didn't work at all.
I debugged whether which line of code was being executed and it didn't execute after `Directory.SetCurrentDirectory(jarRoot);`. Not working from `var pipeline = new StanfordCoreNLP(props);` till below.

My Windows is 64bit, My IIS Express and Visual Studio 2013 are also 64bit.
How am I supposed to do then? How to create a new thread to run annotator? Could you give me the full code? I stuck with this for a week. Really need a help. Thank you very much

**Comment by mehmetilker** [comment]
@hendyharf annotators are tokenize, ssplit and parse. So you should remove just parse.
it should be like this: props.setProperty("annotators", "tokenize, ssplit");

**Comment by hendyharf** [comment]
@mehmetilker I got it, but exactly what I really want to do with Stanford CoreNLP dependency parser, so I need to write the "parse". Any other ideas? I still can't figure it out.

**Comment by hendyharf** [comment]
Hey @sergey-tihon @mehmetilker I've already had the answer for this issue. I'm doing this with Local IIS and it works sometimes, I still got the StackOverflowException. How am I supposed to do to make a larger size stack? The code you've given it doesn't work. It's not returning anything if I write inside the thread. Any other code? I'm stuck with this 3 weeks. Thanks

**Comment by mehmetilker** [comment]
I guess you need first check if your OS 64bit.
After that you need  to be sure if your IIS express is working in 64bit mode.
http://stackoverflow.com/questions/10202047/cant-get-iis-express-8-beta-to-run-website-as-64-bit-process
It looks like it is not possible before VS 2013
https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/3254745-allow-for-iis-express-64-bit-to-run-from-visual-st

If you are sure you OS is 64 bit and service or Express IIS is working in 64 bit mode and you still getting same error then your problem should be something else.

**Comment by mehmetilker** [comment]
Another setting for 64bit IIS Express
https://blogs.msdn.microsoft.com/rob/2013/11/14/debugging-vs2013-websites-using-64-bit-iis-express/
