### ISSUE TITLE
Timex not converting to actual time

### ISSUE THREAD

**Issue by R2dical** [sergey-tihon/Stanford.NLP.NET#48]
I have the following code:

<pre style="font-family:Consolas;font-size:13;color:gainsboro;background:#1e1e1e;">
<span style="color:#57a64a;">//&nbsp;Path&nbsp;to&nbsp;the&nbsp;folder&nbsp;with&nbsp;models&nbsp;extracted&nbsp;from&nbsp;`stanford-corenlp-3.6.0-models.jar`</span>
<span style="color:#569cd6;">var</span>&nbsp;folderPath&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#4ec9b0;">HttpContext</span><span style="color:#b4b4b4;">.</span>Current<span style="color:#b4b4b4;">.</span>Server<span style="color:#b4b4b4;">.</span>MapPath(<span style="color:#d69d85;">&quot;~/App_Data/stanford-corenlp-full-2015-12-09&quot;</span>);
<span style="color:#569cd6;">var</span>&nbsp;modelsFolderPath&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#4ec9b0;">Path</span><span style="color:#b4b4b4;">.</span>Combine(folderPath,&nbsp;<span style="color:#d69d85;">&quot;models&quot;</span>);
 
<span style="color:#57a64a;">//&nbsp;SUTime&nbsp;configuration</span>
<span style="color:#569cd6;">var</span>&nbsp;suTimeFolderPath&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#4ec9b0;">Path</span><span style="color:#b4b4b4;">.</span>Combine(folderPath,&nbsp;<span style="color:#d69d85;">&quot;sutime&quot;</span>);
<span style="color:#569cd6;">var</span>&nbsp;suTimeRules&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#569cd6;">new</span>[]&nbsp;{&nbsp;<span style="color:#d69d85;">&quot;defs.sutime.txt&quot;</span>,&nbsp;<span style="color:#d69d85;">&quot;english.holidays.sutime.txt&quot;</span>,&nbsp;<span style="color:#d69d85;">&quot;english.sutime.txt&quot;</span>&nbsp;}<span style="color:#b4b4b4;">.</span>Select(suTimeRule&nbsp;<span style="color:#b4b4b4;">=&gt;</span>&nbsp;<span style="color:#4ec9b0;">Path</span><span style="color:#b4b4b4;">.</span>Combine(suTimeFolderPath,&nbsp;suTimeRule));
 
<span style="color:#569cd6;">var</span>&nbsp;coreProperties&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#569cd6;">new</span>&nbsp;<span style="color:#4ec9b0;">Properties</span>();
coreProperties<span style="color:#b4b4b4;">.</span>setProperty(<span style="color:#d69d85;">&quot;annotators&quot;</span>,&nbsp;requestProperties<span style="color:#b4b4b4;">.</span>Annotators);
coreProperties<span style="color:#b4b4b4;">.</span>setProperty(<span style="color:#d69d85;">&quot;date&quot;</span>,&nbsp;<span style="color:#4ec9b0;">DateTime</span><span style="color:#b4b4b4;">.</span>Parse(requestProperties<span style="color:#b4b4b4;">.</span>Date)<span style="color:#b4b4b4;">.</span>ToShortDateString());
<span style="color:#57a64a;">//&nbsp;http://stanfordnlp.github.io/CoreNLP/ner.html</span>
coreProperties<span style="color:#b4b4b4;">.</span>setProperty(<span style="color:#d69d85;">&quot;ner.useSUTime&quot;</span>,&nbsp;<span style="color:#d69d85;">&quot;true&quot;</span>);
<span style="color:#57a64a;">//http://nlp.stanford.edu/software/sutime.shtml</span>
coreProperties<span style="color:#b4b4b4;">.</span>setProperty(<span style="color:#d69d85;">&quot;sutime.rules&quot;</span>,&nbsp;<span style="color:#569cd6;">string</span><span style="color:#b4b4b4;">.</span>Join(<span style="color:#d69d85;">&quot;,&quot;</span>,&nbsp;suTimeRules));
coreProperties<span style="color:#b4b4b4;">.</span>setProperty(<span style="color:#d69d85;">&quot;sutime.binders&quot;</span>,&nbsp;<span style="color:#d69d85;">&quot;0&quot;</span>);
<span style="color:#57a64a;">//coreProperties.setProperty(&quot;sutime.markTimeRanges&quot;,&nbsp;&quot;true&quot;);</span>
 
<span style="color:#57a64a;">//&nbsp;We&nbsp;should&nbsp;change&nbsp;current&nbsp;directory,&nbsp;so&nbsp;StanfordCoreNLP&nbsp;could&nbsp;find&nbsp;all&nbsp;the&nbsp;model&nbsp;files&nbsp;automatically</span>
<span style="color:#569cd6;">var</span>&nbsp;curDir&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#4ec9b0;">Environment</span><span style="color:#b4b4b4;">.</span>CurrentDirectory;
<span style="color:#4ec9b0;">Directory</span><span style="color:#b4b4b4;">.</span>SetCurrentDirectory(modelsFolderPath);
<span style="color:#569cd6;">var</span>&nbsp;pipeline&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#569cd6;">new</span>&nbsp;<span style="color:#4ec9b0;">StanfordCoreNLP</span>(coreProperties);
<span style="color:#4ec9b0;">Directory</span><span style="color:#b4b4b4;">.</span>SetCurrentDirectory(curDir);
 
<span style="color:#569cd6;">var</span>&nbsp;props&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#569cd6;">new</span>&nbsp;<span style="color:#4ec9b0;">Properties</span>();
props<span style="color:#b4b4b4;">.</span>setProperty(<span style="color:#d69d85;">&quot;sutime.rules&quot;</span>,&nbsp;<span style="color:#569cd6;">string</span><span style="color:#b4b4b4;">.</span>Join(<span style="color:#d69d85;">&quot;,&quot;</span>,&nbsp;suTimeRules));
props<span style="color:#b4b4b4;">.</span>setProperty(<span style="color:#d69d85;">&quot;sutime.binders&quot;</span>,&nbsp;<span style="color:#d69d85;">&quot;0&quot;</span>);
 
pipeline<span style="color:#b4b4b4;">.</span>addAnnotator(<span style="color:#569cd6;">new</span>&nbsp;<span style="color:#4ec9b0;">TimeAnnotator</span>(<span style="color:#d69d85;">&quot;sutime&quot;</span>,&nbsp;props));
 
<span style="color:#569cd6;">var</span>&nbsp;decodedValue&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#4ec9b0;">HttpUtility</span><span style="color:#b4b4b4;">.</span>UrlDecode(value);
<span style="color:#569cd6;">var</span>&nbsp;annotation&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#569cd6;">new</span>&nbsp;<span style="color:#4ec9b0;">Annotation</span>(decodedValue);
annotation<span style="color:#b4b4b4;">.</span>set(<span style="color:#569cd6;">new</span>&nbsp;<span style="color:#4ec9b0;">CoreAnnotations</span><span style="color:#b4b4b4;">.</span><span style="color:#4ec9b0;">DocDateAnnotation</span>()<span style="color:#b4b4b4;">.</span>getClass(),&nbsp;<span style="color:#4ec9b0;">DateTime</span><span style="color:#b4b4b4;">.</span>Parse(requestProperties<span style="color:#b4b4b4;">.</span>Date)<span style="color:#b4b4b4;">.</span>ToShortDateString());
pipeline<span style="color:#b4b4b4;">.</span>annotate(annotation);
 
<span style="color:#569cd6;">using</span>&nbsp;(<span style="color:#569cd6;">var</span>&nbsp;stream&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#569cd6;">new</span>&nbsp;<span style="color:#4ec9b0;">ByteArrayOutputStream</span>())
{
	<span style="color:#569cd6;">using</span>&nbsp;(<span style="color:#569cd6;">var</span>&nbsp;printWriter&nbsp;<span style="color:#b4b4b4;">=</span>&nbsp;<span style="color:#569cd6;">new</span>&nbsp;<span style="color:#4ec9b0;">PrintWriter</span>(stream))
	{
		pipeline<span style="color:#b4b4b4;">.</span>jsonPrint(annotation,&nbsp;printWriter);
		<span style="color:#569cd6;">return</span>&nbsp;Ok(<span style="color:#4ec9b0;">JsonConvert</span><span style="color:#b4b4b4;">.</span>DeserializeObject(stream<span style="color:#b4b4b4;">.</span>toString()));
	}
}</pre>

Call with the following properies: 
<code>{ "annotators": "tokenize,ssplit,pos,parse,depparse,lemma,ner", "date": "2016-07-30T20:13:22.157Z" }</code>

And tokens like so:
`"tokens": [
        {
          "index": 1,
          "word": "now",
          "originalText": "now",
          "lemma": "now",
          "characterOffsetBegin": 0,
          "characterOffsetEnd": 3,
          "pos": "RB",
          "ner": "DATE",
          "normalizedNER": "PRESENT_REF",
          "before": "",
          "after": "",
          "timex": {
            "tid": "t1",
            "type": "DATE",
            "value": "PRESENT_REF"
          }
        }
      ]
`

With text: <code>Now</code>

Why is 'PRESENT_REF' not converted to the actual time?

Thanks to anyone for any assistance!

**Comment by sergey-tihon** [comment]
@R2dical I really recommend to repeat the question on SO - http://stackoverflow.com/questions/tagged/stanford-nlp

This project is for recompiling `*.jar`s to `*.dll`s, and all questions like "How to write in C# the following Java code".

Sorry, I do not know answers on all `Stanford.NLP` question like "Why it works so".
