### ISSUE TITLE
Can we have a sample for simple API usage?

### ISSUE THREAD

**Issue by nefcanto** [sergey-tihon/Stanford.NLP.NET#49]
The samples existing in the samples directory are good to start. Yet as soon as I change from them, because of the lack of documentation, I encounter many weird Java exceptions and I can't find the problems through searching.

Can we have a sample for simple API calls? I'm talking a sample for this URL:
[http://stanfordnlp.github.io/CoreNLP/simple.html](http://stanfordnlp.github.io/CoreNLP/simple.html)

Also can we have a sample of how to access annotations (result of NLP annotators) directly in C#, and not pretty print them to the console?

**Comment by sergey-tihon** [comment]
Sample is available [here](http://sergey-tihon.github.io/Stanford.NLP.NET/StanfordSUTime.html) for example.
It is a little bit tricky, but you have to create instance of annotation class and call `.getClass()`.
```csharp
new CoreAnnotations.TextAnnotation().getClass()
```
more
```csharp
// Sample text for time expression extraction
var text = "Three interesting dates are 18 Feb 1997, the 20th of july and 4 days from today.";
var annotation = new Annotation(text);
annotation.set(new CoreAnnotations.DocDateAnnotation().getClass(), "2013-07-14");
pipeline.annotate(annotation);

Console.WriteLine("{0}\n", annotation.get(new CoreAnnotations.TextAnnotation().getClass()));

var timexAnnsAll = annotation.get(new TimeAnnotations.TimexAnnotations().getClass()) as ArrayList;
foreach (CoreMap cm in timexAnnsAll)
{
    var tokens = cm.get(new CoreAnnotations.TokensAnnotation().getClass()) as List;
    var first = tokens.get(0);
    var last = tokens.get(tokens.size() - 1);
    var time = cm.get(new TimeExpression.Annotation().getClass()) as TimeExpression;
    Console.WriteLine("{0} [from char offset {1} to {2}] --> {3}", cm, first, last, time.getTemporal());
}
```

**Comment by sergey-tihon** [comment]
Added [Simple CoreNLP](http://sergey-tihon.github.io/Stanford.NLP.NET//samples/CoreNLP.Simple.html) samples translated to .NET
