### ISSUE TITLE
openie.resolve_coref bug in 3.6.0 release

### ISSUE THREAD

**Issue by ErikOmberg** [sergey-tihon/Stanford.NLP.NET#50]
The bug detailed here is also in the current Nuget release:
http://stackoverflow.com/questions/35921678/stanford-openie-with-option-openie-resolve-coref-dont-work

The stackoverflow post sounds like it's fixed on the Stanford GitHub head, but not yet in the official maven release. Do you do updates occasionally to the GitHub head, or do you only update when there's an official maven release?

If you don't plan to update to the GitHub head, could you please direct me at the ikvm build script you use to convert the jar in to your Stanfor.Nlp.Net DLL? 

I've used ikvm before, but I want to make sure I get all of the dependencies rolled in to the DLL correctly if there are things other than just the one stanford-corenlp.jar that need conversion.
Thank you.

**Comment by sergey-tihon** [comment]
I do updates directly from ` http://nlp.stanford.edu/`
https://github.com/sergey-tihon/Stanford.NLP.NET/blob/master/paket.dependencies#L14-L18
I do not compile Java here at all.

Do you know when next release will be? It should be really soon.

**Comment by sergey-tihon** [comment]
@stanfordnlp when do you plan next release of `CoreNLP` ?

**Comment by ErikOmberg** [comment]
Looks like a beta 3.7.0.0 just came out:
http://stanfordnlp.github.io/CoreNLP/download.html
http://nlp.stanford.edu/software/stanford-corenlp-full-2016-10-30.zip

**Comment by sergey-tihon** [comment]
First of all new KBP models are not win-friendly, so trick with changing current directory does not help you to load KBP models.  If you want to use them in beta version you have to specify paths to all model files manually. - https://github.com/stanfordnlp/CoreNLP/issues/293

The `3.7.0.0-beta` version is available on NuGet:
https://www.nuget.org/packages/Stanford.NLP.CoreNLP/3.7.0-beta

**Comment by ErikOmberg** [comment]
Thank you very much for the update. The simple example is now working:
Obama was born in Hawaii. He is our president.
