### ISSUE TITLE
Problem while trying to run corenlp example as a Forms application

### ISSUE THREAD

**Issue by rbwater** [sergey-tihon/Stanford.NLP.NET#51]
Hi,

Not sure if this is the right place to ask this type of question but hopefully you can help.  I was trying to run the coreNLP example as a Forms application rather than a Console application.  It fails to compile because there is a conflict between the java Properties class and a pre-existing C# Properties class at this line: var props = new Properties();. I think this can be resolved by referring to the full namespace for the java Properties but I can't seem to find what that is.  Would you know the namespace or be able to tell me how to find it.

Thanks,

RB

**Comment by sergey-tihon** [comment]
use probably use following three
```csharp
using java.util;
using java.io;
using edu.stanford.nlp.pipeline;
```
`Properties` should be in `edu.stanford.nlp.pipeline`

**Comment by rbwater** [comment]
Thanks for getting back to me so quickly and thanks for the hint.  It turned out that Properties is in the java.util so var props = new java.util.Properties(); worked.
RB
