### ISSUE TITLE
Cannot load Models

### ISSUE THREAD

**Issue by diegolinan** [sergey-tihon/Stanford.NLP.NET#52]
I have tried to load the models for the new release as the the source code (very short, very undocumented) that is posted on the initial page states. 
I have unziped the 

and I can't get pos to work. when removing flags (to at least try to make this thing work) I can only get "tokenize" and "ssplit" to work. When I remove flags and get to "dcoref" I get the following message:

An unhandled exception of type 'java.lang.RuntimeException' occurred in stanford-corenlp-3.6.0.dll

Additional information: edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Unable to open "edu/stanford/nlp/models/dcoref/demonyms.txt" as class path, filename or URL

I am using the following code

```
    class Program
    {
        static void Main(string[] args)
        {
            // Path to the folder with models extracted from `stanford-corenlp-3.6.0-models.jar`
            var jarRoot = @"edu\stanford\nlp\models";

            // Text for processing
            var text = "Kosgi Santosh sent an email to Stanford University. He didn't get a reply.";

            // Annotation pipeline configuration
            var props = new Properties();
            //props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, parse, dcoref");
            props.setProperty("annotators", "tokenize, ssplit, dcoref");
            props.setProperty("ner.useSUTime", "0");

            // We should change current directory, so StanfordCoreNLP could find all the model files automatically
            var curDir = Environment.CurrentDirectory;
            Directory.SetCurrentDirectory(jarRoot);
            var pipeline = new StanfordCoreNLP(props);
            Directory.SetCurrentDirectory(curDir);

            // Annotation
            var annotation = new Annotation(text);
            pipeline.annotate(annotation);

            // Result - Pretty Print
            using (var stream = new ByteArrayOutputStream())
            {
                pipeline.prettyPrint(annotation, new PrintWriter(stream));
                Console.WriteLine(stream.toString());
                stream.close();
            }

            Console.ReadLine();
        }
    }
```

The files are copied to my debug directory, no matter what I put on the jarRoot var, I keep getting errors or statements saying that some file is missing, or that a model could not be found.

can you give a simple walkthrough as to where is it that you copy the uncompressed jar file?
where do you get it from?
which jar file is the current one for this version of the engine?

**Comment by sergey-tihon** [comment]
`jarRoot` should point to the root directory that contains file `edu/stanford/nlp/models/dcoref/demonyms.txt`.

In other words, `edu/stanford/nlp/models/dcoref/demonyms.txt` should be resolvable as relative path from `jarRoot` directory

**Comment by diegolinan** [comment]
Same applies to all the rest?

**Comment by diegolinan** [comment]
I have placed my model files like this:
![image](https://cloud.githubusercontent.com/assets/2962970/19158431/0e8012fe-8bbf-11e6-97d7-c21a00d24a92.png)

And still, with this code, I get that some files are missing... 

```
using System;
using System.IO;
using java.util;
using java.io;
using edu.stanford.nlp.pipeline;
using Console = System.Console;

namespace StanfordPosTagger
{
    class Program
    {
        static void Main(string[] args)
        {
            // Path to the folder with models extracted from `stanford-corenlp-3.6.0-models.jar`
            var jarRoot = @"..\..\..\..\..\..\..\nlp\edu\stanford\nlp\models";

            // Text for processing
            var text = "Kosgi Santosh sent an email to Stanford University. He didn't get a reply.";

            // Annotation pipeline configuration
            var props = new Properties();
            props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, parse, dcoref");
            props.setProperty("sutime.binders", "0");
            props.setProperty("ner.useSUTime", "0");

            // We should change current directory, so StanfordCoreNLP could find all the model files automatically
            var curDir = Environment.CurrentDirectory;
            Directory.SetCurrentDirectory(jarRoot);
            var pipeline = new StanfordCoreNLP(props);
            Directory.SetCurrentDirectory(curDir);

            // Annotation
            var annotation = new Annotation(text);
            pipeline.annotate(annotation);

            // Result - Pretty Print
            using (var stream = new ByteArrayOutputStream())
            {
                pipeline.prettyPrint(annotation, new PrintWriter(stream));
                Console.WriteLine(stream.toString());
                stream.close();
            }

            Console.ReadLine();
        }
    }
}
```

should I use and older model...?
Which one are you using?

**Comment by sergey-tihon** [comment]
if your case `jarRoot` should be `c:\\nlp\\`.

Basically you have 2 options:
1) unzip `jar` and point `jarRoot` to the place where you extracted files from `jar` (and change current directory
2) specify path to each model manually - https://github.com/sergey-tihon/Stanford.NLP.NET/blob/master/tests/Stanford.NLP.CoreNLP.FSharp.Tests/CoreNLP.fs#L96

**Comment by diegolinan** [comment]
I've gone with a mix of the latter and some other stuff. For those out there with the same issue:

1) Copy the whole "edu" folder and its subfolders to your Visual Studio project
2) Go through each of the folders (ALL OF THEM) and select all the files you find on each folder and include them as "content" in your project. Select also the "Copy if newer" option, like so:

![image](https://cloud.githubusercontent.com/assets/2962970/19189411/47c0806c-8c6e-11e6-8f30-53d2ecaa57dc.png)

3) Compile the project so that all the files and folders get copied into the debug folder. What this basically does is that it will let the engine find those files with relative paths because they reside in the same executing assembly folder.
4) Use the following code and moidify to your need. In this case, I'm using it to parse the response as json.

`using java.util;
using edu.stanford.nlp.pipeline;
using Console = System.Console;
using StringWriter = java.io.StringWriter;

namespace StanfordPosTagger
{
    class Program
    {
        static void Main(string[] args)
        {
            var props = new Properties();
            props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, parse, dcoref");
            props.setProperty("pos.model",
                @"edu\stanford\nlp\models\pos-tagger\english-bidirectional\english-bidirectional-distsim.tagger");
            props.setProperty("ner.model", @"edu\stanford\nlp\models\ner\english.all.3class.distsim.crf.ser.gz");
            props.setProperty("parse.model", @"edu\stanford\nlp\models\lexparser\englishPCFG.ser.gz");
            props.setProperty("dcoref.demonym", @"edu\stanford\nlp\models\dcoref\demonyms.txt");
            props.setProperty("dcoref.states", @"edu\stanford\nlp\models\dcoref\state-abbreviations.txt");
            props.setProperty("dcoref.animate", @"edu\stanford\nlp\models\dcoref\animate.unigrams.txt");
            props.setProperty("dcoref.inanimate", @"edu\stanford\nlp\models\dcoref\inanimate.unigrams.txt");
            props.setProperty("dcoref.male", @"edu\stanford\nlp\models\dcoref\male.unigrams.txt");
            props.setProperty("dcoref.neutral", @"edu\stanford\nlp\models\dcoref\neutral.unigrams.txt");
            props.setProperty("dcoref.female", @"edu\stanford\nlp\models\dcoref\female.unigrams.txt");
            props.setProperty("dcoref.plural", @"edu\stanford\nlp\models\dcoref\plural.unigrams.txt");
            props.setProperty("dcoref.singular", @"edu\stanford\nlp\models\dcoref\singular.unigrams.txt");
            props.setProperty("dcoref.countries", @"edu\stanford\nlp\models\dcoref\countries");
            props.setProperty("dcoref.extra.gender", @"edu\stanford\nlp\models\dcoref\namegender.combine.txt");
            props.setProperty("dcoref.states.provinces", @"edu\stanford\nlp\models\dcoref\statesandprovinces");
            props.setProperty("dcoref.singleton.predictor", @"edu\stanford\nlp\models\dcoref\singleton.predictor.ser");
            props.setProperty("dcoref.big.gender.number", @"edu\stanford\nlp\models\dcoref\gender.map.ser.gz");
            props.setProperty("sutime.rules", @"edu\stanford\nlp\models\sutime\defs.sutime.txt, edu\stanford\nlp\models\sutime\english.holidays.sutime.txt, edu\stanford\nlp\models\sutime\english.sutime.txt");
            props.setProperty("sutime.binders", "0");
            props.setProperty("ner.useSUTime", "0");

            var pipeline = new StanfordCoreNLP(props);

            var text = "Kosgi Santosh sent an email to Stanford University. He didn't get a reply.";

            // Annotation
            var annotation = new Annotation(text);
            pipeline.annotate(annotation);

            var stringWriter = new StringWriter();

            pipeline.jsonPrint(annotation, stringWriter);

            Console.WriteLine(stringWriter.toString());

            Console.ReadLine();
        }
    }
}
`

**Comment by sergey-tihon** [comment]
Does it mean that this issue is fixed?

**Comment by diegolinan** [comment]
Well... I think it just means that there is a workaround to it at least. I could never make it work with the example on the stanford page though. So I leave it to you to decide (-:

**Comment by sergey-tihon** [comment]
Why not? If you do not include models in project and do not copy them during build... everything is simple:
1) [Unzip to some folder](https://github.com/sergey-tihon/Stanford.NLP.NET/blob/master/tests/Stanford.NLP.CoreNLP.FSharp.Tests/Config.fs#L4)
2) Change current directory temporary during model loading.

it is simple, is not it?

**Comment by diegolinan** [comment]
It shoudl, yes. I really don't know what to tell you... I tried it that way and it didn't work. Always a file was missing or it was unable to bind the models... Maybe I am doing something wrong, but I did it as you described and as it was on the provided example and it did not work for me.

**Comment by sergey-tihon** [comment]
You mentioned new release, where did you get it from?

**Comment by diegolinan** [comment]
These are the latest for english
http://nlp.stanford.edu/software/stanford-english-corenlp-2016-01-10-models.jar
