### ISSUE TITLE
StanfordCoreNlp object hangs when loading NER classifiers

### ISSUE THREAD

**Issue by zanek** [sergey-tihon/Stanford.NLP.NET#54]
This is quite odd. If I compile my project as 32-bit, it loads the classifiers just fine and everything works.

If I compile the project as 64-bit  it starts loading all the NER classifiers and and then hangs on the english.4class.conll.distsim.crf.ser.gz  model. Loading the models before that are really slow on 64-bit, but it never finishes loading the conll model (I've left it running for 30+ min)

Does anyone have any idea why this would happen on 64-bit only ?

**Comment by sergey-tihon** [comment]
Just did a comparison on tests projects - I do not see such issue
https://github.com/sergey-tihon/Stanford.NLP.NET/issues/40#issuecomment-254610544

**Comment by vermouthmjl** [comment]
I also have this problem. When I do not load NER annotator, everything works fine. When I only load NER, memory use caps at about 500MB, then nothing happens, and the program hangs.

I'm using the nuget package Stanford.NLP.CoreNLP 3.9.1.0 in C#, for net45, in x64.

Here is the subtree provided by the profiler from the moment we instantiate the StanfordCoreNLP object:
78.82%   StanfordCoreNLP..ctor  •  39,444 ms  •  edu.stanford.nlp.pipeline.StanfordCoreNLP..ctor
  78.82%   StanfordCoreNLP..ctor  •  39,444 ms  •  edu.stanford.nlp.pipeline.StanfordCoreNLP..ctor
    78.82%   StanfordCoreNLP..ctor  •  39,444 ms  •  edu.stanford.nlp.pipeline.StanfordCoreNLP..ctor
      78.78%   construct  •  39,426 ms  •  edu.stanford.nlp.pipeline.StanfordCoreNLP.construct
        78.47%   get  •  39,269 ms  •  edu.stanford.nlp.pipeline.AnnotatorPool.get
          78.47%   get  •  39,269 ms  •  edu.stanford.nlp.util.Lazy.get
            78.47%   compute  •  39,269 ms  •  edu.stanford.nlp.util.Lazy+3.compute
              78.47%   get  •  39,269 ms  •  edu.stanford.nlp.pipeline.StanfordCoreNLP+__<>Anon38.get
                78.47%   lambda$null$69  •  39,269 ms  •  edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$null$69
                  78.47%   apply  •  39,269 ms  •  edu.stanford.nlp.pipeline.StanfordCoreNLP+__<>Anon8.apply
                    78.47%   lambda$getNamedAnnotators$46  •  39,269 ms  •  edu.stanford.nlp.pipeline.StanfordCoreNLP.lambda$getNamedAnnotators$46
                      78.47%   tokensRegexNER  •  39,269 ms  •  edu.stanford.nlp.pipeline.AnnotatorImplementations.tokensRegexNER
                        78.45%   TokensRegexNERAnnotator..ctor  •  39,263 ms  •  edu.stanford.nlp.pipeline.TokensRegexNERAnnotator..ctor
                          62.04%   createPatternMatcher  •  31,050 ms  •  edu.stanford.nlp.pipeline.TokensRegexNERAnnotator.createPatternMatcher
                            61.71%   getNewEnv  •  30,883 ms  •  edu.stanford.nlp.ling.tokensregex.TokenSequencePattern.getNewEnv
                              61.69%   TokenSequenceParser..ctor  •  30,871 ms  •  edu.stanford.nlp.ling.tokensregex.parser.TokenSequenceParser..ctor
                                61.69%   TokenSequenceParser+LookaheadSuccess..ctor  •  30,871 ms  •  edu.stanford.nlp.ling.tokensregex.parser.TokenSequenceParser+LookaheadSuccess..ctor
                                  61.69%   TokenSequenceParser+LookaheadSuccess..ctor  •  30,871 ms  •  edu.stanford.nlp.ling.tokensregex.parser.TokenSequenceParser+LookaheadSuccess..ctor
                                    61.69%   Error..ctor  •  30,871 ms  •  java.lang.Error..ctor
                                      61.69%   Throwable..ctor  •  30,871 ms  •  java.lang.Throwable..ctor
                                        61.69%   fillInStackTrace  •  30,871 ms  •  java.lang.Throwable.fillInStackTrace
                                           61.69%   CaptureStackTrace  •  30,871 ms  •  System.Diagnostics.StackTrace.CaptureStackTrace
                              ►0.02%   initDefaultBindings  •  12 ms  •  edu.stanford.nlp.ling.tokensregex.Env.initDefaultBindings
                            ►0.11%   valueOf  •  53 ms  •  edu.stanford.nlp.ling.tokensregex.CoreMapNodePattern.valueOf
                            ►0.09%   add  •  48 ms  •  java.util.ArrayList.add
                            ►0.07%   [Native code]  •  36 ms
                            ►0.06%   compile  •  30 ms  •  edu.stanford.nlp.ling.tokensregex.TokenSequencePattern.compile
                          ►16.35%   readEntries  •  8,183 ms  •  edu.stanford.nlp.pipeline.TokensRegexNERAnnotator.readEntries
                          ►0.04%   valueOf  •  18 ms  •  edu.stanford.nlp.pipeline.TokensRegexNERAnnotator+PosMatchType.valueOf
                          ►0.01%   lookupAnnotationKeyWithClassname  •  6 ms  •  edu.stanford.nlp.ling.tokensregex.EnvLookup.lookupAnnotationKeyWithClassname
        ►0.16%   info  •  78 ms  •  edu.stanford.nlp.util.logging.Redwood+RedwoodChannels.info
        ►0.14%   [Native code]  •  72 ms
      ►0.02%   constructAnnotatorPool  •  12 ms  •  edu.stanford.nlp.pipeline.StanfordCoreNLP.constructAnnotatorPool

**Comment by sergey-tihon** [comment]
Close as an old issue
