### ISSUE TITLE
c# Load Model

### ISSUE THREAD

**Issue by aliNader** [sergey-tihon/Stanford.NLP.NET#61]
I have installed stanford-postagger-3.7.0 and the models and put it within the project, then write the below code
```csharp
            // Loading POS Tagger
            var tagger = new MaxentTagger(@"models\arabic-train.tagger"); // This line throw the exception

            // Text for tagging
            var text = "خطأ أثناء تحميل الموديل";

            var sentences = MaxentTagger.tokenizeText(new java.io.StringReader(text)).toArray();
            foreach (List sentence in sentences)
            {
                var taggedSentence = tagger.tagSentence(sentence);
                Console.WriteLine(taggedSentence);
            }
```
but when i execute it,  IO Exception is thrown said "Unable to open "models\arabic-train.tagger" as class path, filename or URL"
please help.

**Comment by sergey-tihon** [comment]
Check that `current directory`+`models\arabic-train.tagger` is exist on your drive

**Comment by aliNader** [comment]
@sergey-tihon 
it is Exist in the project directory
![capture](https://cloud.githubusercontent.com/assets/26377780/23858165/3ba75ea2-0808-11e7-8d4d-7c47361dbc8c.PNG)

**Comment by sergey-tihon** [comment]
but it does not mean that you copy files to target directory and does not mean that in the runtime you `Environment.CurrentDirectory` is equal to build target directory.

Please, put breakpoint on the like ` var tagger = new MaxentTagger(@"models\arabic-train.tagger");` and debug your current directory.

**Comment by sergey-tihon** [comment]
I hope that this is resolved already, if not - please read this http://sergey-tihon.github.io/Stanford.NLP.NET//faq.html#Stanford-NLP-CoreNLP-not-loading-models

**Comment by aliNader** [comment]
it is resolved, thanks :)


2017-05-02 7:00 GMT+03:00 Sergey Tihon <notifications@github.com>:
