### ISSUE TITLE
stanford nlp (tagger+sentiments)

### ISSUE THREAD

**Issue by SnehaCoder** [sergey-tihon/Stanford.NLP.NET#64]
My code:

```csharp
            var jarRoot = @"D:\SmartPrj\IntentenetMessage\SampleAPP\IntenetMessage\stanford-postagger-full-2016-10-31\";

            var tagger = new MaxentTagger(@"D:\SmartPrj\IntentenetMessage\SampleAPP\IntenetMessage\stanford-postagger-full-2016-10-31\models\wsj-0-18-bidirectional-distsim.tagger");// for tagger model error removal

            // Text for processing
            var text = "Hi. Hello !";

            // Annotation pipeline configuration
            var props = new java.util.Properties();

            props.setProperty("annotators", "tokenize, ssplit, pos, sentiment");//, lemma, ner, parse, dcoref
            props.setProperty("sutime.binders", "0");
            props.setProperty("ner.useSUTime", "false");

            // We should change current directory, so D:\Core NLP Files\stanford-corenlp-full-2015-04-20\stanford-corenlp-full-2015-04-20 could find all the model files automatically
            var curDir = Environment.CurrentDirectory;
            Directory.SetCurrentDirectory(jarRoot);
            var pipeline = new StanfordCoreNLP(props);
            Directory.SetCurrentDirectory(curDir);

            // Annotation
            var annotation = new edu.stanford.nlp.pipeline.Annotation(text);
            pipeline.annotate(annotation);

            // Result - Pretty Print
            using (var stream = new ByteArrayOutputStream())
            {
                pipeline.prettyPrint(annotation, new PrintWriter(stream));

                //Analyze the statement as positive or negative


                int mainSentiment = 0;
                int longest = 0;
                String[] sentimentText = { "Very Negative", "Negative", "Neutral", "Positive", "Very Positive" };

                NumberFormat NF = new DecimalFormat("0.0000");

                //for (CoreMap sentence : document.get(CoreAnnotations.SentencesAnnotation.class)) 

                var sentences = annotation.get(new CoreAnnotations.SentencesAnnotation().getClass()) as ArrayList;

                foreach (CoreMap sentence in sentences)
                {
                    java.lang.Class treeClass = new edu.stanford.nlp.trees.TreeCoreAnnotations.TreeAnnotation().getClass();

                    Tree tree = (Tree)sentence.get(typeof(SentimentCoreAnnotations.SentimentAnnotatedTree));

                    try
                    {
                        int sentiment = RNNCoreAnnotations.getPredictedClass(tree);
                        String partText = sentence.ToString();
                        String a = "Sentence: '" + partText + "' is rather " + sentimentText[sentiment];

                        if (partText.Length > longest)
                        {
                            mainSentiment = sentiment;
                            longest = partText.Length;
                        }
                    }
                    catch (Exception ex)
                    {
                        throw;
                    }
                }


                switch (mainSentiment)
                {
                    case 0:
                        return "Very Negative";
                    case 1:
                        return "Negative";
                    case 2:
                        return "Neutral";
                    case 3:
                        return "Positive";
                    case 4:
                        return "Very Positive";
                    default:
                        return "";
                }

                stream.close();
            }
        }
```

I downloaded the zip from 
http://sergey-tihon.github.io/Stanford.NLP.NET/StanfordPOSTagger.html
https://www.nuget.org/packages/Stanford.NLP.CoreNLP/3.7.0

![img1](https://cloud.githubusercontent.com/assets/28148533/25531597/f7d87198-2c47-11e7-8d7d-f535d4a25b5d.png)
![img2](https://cloud.githubusercontent.com/assets/28148533/25531598/f7e304b4-2c47-11e7-9710-ce8a14e90218.png)

**Comment by sergey-tihon** [comment]
You use CoreNLP package, https://www.nuget.org/packages/Stanford.NLP.CoreNLP/3.7.0
so you have to follow this manual http://sergey-tihon.github.io/Stanford.NLP.NET/StanfordCoreNLP.html

and download CoreNLP model http://nlp.stanford.edu/software/stanford-corenlp-full-2016-10-31.zip 

You do not need `MaxentTagger`, `StanfordCoreNLP` pipeline do everything for you.

CoreNLP is super set of API and model, when you use it - you need nothing else.

**Comment by SnehaCoder** [comment]
Sergey, the stanford nlp the last updated on Friday, January 13, 2017, package i should download?
or there is one more new one named latest version ?

**Comment by SnehaCoder** [comment]
Sergey,do i need to download "Stanford CoreNLP ZIP archive with models"" too? from this link u sent me http://sergey-tihon.github.io/Stanford.NLP.NET/StanfordCoreNLP.html

**Comment by sergey-tihon** [comment]
Yes, this is the link  http://nlp.stanford.edu/software/stanford-corenlp-full-2016-10-31.zip
in this archive you will find `jar` with models that you need to unzip

**Comment by SnehaCoder** [comment]
![img_2942017](https://cloud.githubusercontent.com/assets/28148533/25553235/abf33130-2ccb-11e7-95d8-f3b59e9c4cce.png)

i downloaded n pls check the folders.. please tell me is it correct

**Comment by SnehaCoder** [comment]
![img_2942017_1](https://cloud.githubusercontent.com/assets/28148533/25553412/211c295e-2cd0-11e7-8bc3-1145a6204a33.png)
![img_2942017_2](https://cloud.githubusercontent.com/assets/28148533/25553413/211d591e-2cd0-11e7-9629-6b577a46bdee.png)
pls check this Sergey.

**Comment by SnehaCoder** [comment]
in this download i cannot find the models folder . do i need to explicitly download models from here https://stanfordnlp.github.io/CoreNLP/
Kindly help.

**Comment by sergey-tihon** [comment]
There is a step in [Getting Started section](http://sergey-tihon.github.io/Stanford.NLP.NET/) 
> Unzip `*.jar` file with models if such one exists.

You have `stanford-corenlp-3.7.0-models.jar` in your folder, this is `zip` archive with models that you have to unzip and `jarRoot` should point to the root of unzipped directory

**Comment by SnehaCoder** [comment]
Sergey, I did as  u said n got the same error as previous even though now i have models folders and contents in it
Attaching image for your reference
![img_2942017_3](https://cloud.githubusercontent.com/assets/28148533/25554755/1d94714c-2cf3-11e7-82a9-0a7800f6cd68.png)

**Comment by sergey-tihon** [comment]
> jarRoot should point to the root of unzipped directory
not to the models folder

Here is your root 
<img width="1052" alt="2017-04-29_1327" src="https://cloud.githubusercontent.com/assets/1197905/25554803/b7ec753c-2cdf-11e7-941c-9a88aacef957.png">

**Comment by sergey-tihon** [comment]
@SnehaCoder Does it work now?

**Comment by sergey-tihon** [comment]
I hope that it is OK now, if it still not - please read the explanation how model loading works
http://sergey-tihon.github.io/Stanford.NLP.NET//faq.html#Stanford-NLP-CoreNLP-not-loading-models

**Comment by SnehaCoder** [comment]
Sorry Sergey, I was out of office for three days.

I tried the above options but still im yet to get success.
![img_02052017_1](https://cloud.githubusercontent.com/assets/28148533/25604791/f7a57ed0-2f23-11e7-8959-51e371b1e6f1.png)

**Comment by sergey-tihon** [comment]
you path is still incorrect, you forgot `/jar/` part to `jar`
Please read carefully why we change current directory during pipeline creation

**Comment by SnehaCoder** [comment]
I am sorry about it,but i have changed the path of my original folder

**Comment by sergey-tihon** [comment]
Than add `stanford-corenlp-3.7.0-models` instead of `jar`

**Comment by SnehaCoder** [comment]
thank u i changed it to the said folder 
![image](https://cloud.githubusercontent.com/assets/28148533/25605157/93744f38-2f26-11e7-9af2-6732591c3880.png)
but now im getting sentiments error

**Comment by sergey-tihon** [comment]
thy annotators order from the exception message, i think that order is matter (it is pipeline)
something like  `"tokenize, ssplit, pos, parse, sentiment"`

**Comment by SnehaCoder** [comment]
Thank you Sergey! U are a GodFather!
Take Care. Thanks a ton once again.
You saved me!

**Comment by SnehaCoder** [comment]
Sergey, Can you please help me with codes for tree representation and also to find percentage of sentiments.

**Comment by sergey-tihon** [comment]
What tree codes?

Take a look at new sample page http://sergey-tihon.github.io/Stanford.NLP.NET//samples.html
there are two links on samples about sentiments. There are 5 sentiment classes, here it sample how to get prop for each class and class with max probability 
https://github.com/evelinag/SentimentAnalysisDemo/blob/master/code/sentiment.fsx#L53-L55

**Comment by SnehaCoder** [comment]
Sergey, I want C# code to display a tree like structure like below: 
Please help.
![image](https://cloud.githubusercontent.com/assets/28148533/25648293/007a4e5e-2fe8-11e7-8591-72d1716377b3.png)

**Comment by sergey-tihon** [comment]
This is dependency parse tree, I did it using Stanford Parser
https://github.com/sergey-tihon/Stanford.NLP.NET/blob/master/samples/Stanford.NLP.Parser.CSharp/Program.cs#L35-L44
But it should be possible to get it from generic Core NLP annotation.
Or you could try "new" 😉 Simple CoreNLP API http://sergey-tihon.github.io/Stanford.NLP.NET//samples/CoreNLP.Simple.html
