### ISSUE TITLE
Unsafe content on HTTPS site

### ISSUE THREAD

**Issue by haf** [sergey-tihon/Stanford.NLP.NET#66]
<img width="1245" alt="screen shot 2017-05-06 at 16 54 33" src="https://cloud.githubusercontent.com/assets/193115/25773384/baab4bb6-327c-11e7-9d42-ba0487199da5.png">

**Comment by sergey-tihon** [comment]
I redeployed new version of site with `https` link.
@haf could you please confirm that it is fixed now?

**Comment by haf** [comment]
Yes, it's fixed.
