### ISSUE TITLE
Invalid stream header with lexparser models

### ISSUE THREAD

**Issue by Perlkonig** [sergey-tihon/Stanford.NLP.NET#68]
I've developed a Word add-in (C# + Visual Studio) that leverages the Stanford parsers. The POS tagger works fine. I've embedded the model file as a resource and successfully instantiate the tagger as follows:

```csharp
var _assembly = Assembly.GetExecutingAssembly();
var _stream = _assembly.GetManifestResourceStream("NAMESPACE.Resources.MODELNAME");
java.io.InputStream model = new ikvm.io.InputStreamWrapper(_stream);
var tagger = new MaxentTagger(model);
```

Now I want to use the `LexicalizedParser` to do some grammatical analysis. I tried the following:

```csharp
var _assembly = Assembly.GetExecutingAssembly();
var _stream = _assembly.GetManifestResourceStream("NAMESPACE.Resources.MODELNAME");
var isw = new ikvm.io.InputStreamWrapper(_stream);
var ois = new java.io.ObjectInputStream(isw);
var lp = LexicalizedParser.loadModel(ois);
```

When I do this, I get an `invalid stream header` error. Google gives me two basic hits:

1. [A StackOverflow post](https://stackoverflow.com/questions/13237505/how-do-i-access-a-net-resource-for-an-ikvm-ported-java-library) gives my exact code. A user noted the same problem, said they resolved it, but they never explained how. ([Obligatory xkcd link](https://xkcd.com/979/))

2. Other posts say this occurs when mismatching the parser version and the model version. I know this isn't happening in this case because I can load the model fine if I point it directly to the file on the local file system. Obviously I want to embed the model for portability.

Any idea how to get around this? Thanks for porting this to .NET! So useful!

**Comment by sergey-tihon** [comment]
What NuGet package do you use? it is CoreNLP, right? and models for CoreNLP?

**Comment by sergey-tihon** [comment]
Seems that I understand the reason of the issue.

The model for `LexicalizedParser` is gziped so you need to swap `ikvm.io.InputStreamWrapper` into `java.util.zip.GZIPInputStream` before passing it into `java.io.ObjectInputStream`

See sample tests:
```fsharp
testList "Load model from stream" [
    test "MaxentTagger" {
        // Plain model in the file
        let model = Models.``pos-tagger``.``english-left3words``.``english-left3words-distsim.tagger``
        use fs = new FileStream(model, FileMode.Open)
        use isw = new ikvm.io.InputStreamWrapper(fs)
        let tagger = edu.stanford.nlp.tagger.maxent.MaxentTagger(isw)
        Expect.isNotNull tagger ""
    }
    ftest "LexicalizedParser" {
        // GZIPed model in the file
        let model = Models.lexparser.``englishRNN.ser.gz``
        use fs = new FileStream(model, FileMode.Open)
        use isw = new ikvm.io.InputStreamWrapper(fs)

        use ois =
            if model.EndsWith(".gz")
            then
                let gzs = new java.util.zip.GZIPInputStream(isw)
                new java.io.ObjectInputStream(gzs)
            else new java.io.ObjectInputStream(isw)
        let lp = edu.stanford.nlp.parser.lexparser.LexicalizedParser.loadModel(ois)
        Expect.isNotNull lp ""
    }
]
```

**Comment by Perlkonig** [comment]
Thank you!!
