### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'IKVM.OpenJDK.Text

### ISSUE THREAD

**Issue by jamessdixon** [sergey-tihon/Stanford.NLP.NET#69]
I am following the tutorial found here.  I have entered the following code into a script:

```fsharp
#r "../packages/Stanford.NLP.Parser.Fsharp.0.0.13/lib/Stanford.NLP.Parser.Fsharp.dll"
#r "../packages/Stanford.NLP.Parser.3.7.0.0/lib/stanford-parser.dll"
#r "../packages/Stanford.NLP.Parser.3.7.0.0/lib/ejml-0.23.dll"
#r "../packages/IKVM.8.1.5717.0/lib/IKVM.Runtime.dll"
#r "../packages/IKVM.8.1.5717.0/lib/IKVM.OpenJDK.Core.dll"
#r "../packages/IKVM.8.1.5717.0/lib/IKVM.OpenJDK.Text.dll"
open edu.stanford.nlp.parser.lexparser
open edu.stanford.nlp.trees
open java.util
open System
open Stanford.NLP.FSharp.Parser

let model = @"..\data\englishPCFG.ser.gz"
let options = [|"-maxLength"; "500";"-retainTmpSubcategories"; "-MAX_ITEMS";
                "500000";"-outputFormat"; "penn,typedDependenciesCollapsed"|]
let parser = LexicalizedParser.loadModel(model, options)
let languagePack = PennTreebankLanguagePack()
let factory = languagePack.grammaticalStructureFactory()
```

I am getting the following error:

> System.TypeInitializationException: The type initializer for 'edu.stanford.nlp.util.Timing' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'IKVM.OpenJDK.Text, Version=8.1.5717.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58' or one of its dependencies. The system cannot find the file specified.
>    at edu.stanford.nlp.util.Timing..cctor()

What am I doing wrong?  I added a "r" to that lib and the exception is still throwing.
Thanks

**Comment by sergey-tihon** [comment]
@jamessdixon Could you share the link to the tutorial that you've used?

Here is the sample for `Stanford Parser`:
https://sergey-tihon.github.io/Stanford.NLP.NET//samples/Parser.Sample.html

It depends on your task, but you may also want to try `Simple CoreNLP` (__another NuGet package__)
https://sergey-tihon.github.io/Stanford.NLP.NET//samples/CoreNLP.Simple.html

**Comment by jamessdixon** [comment]
I used this page: http://sergey-tihon.github.io/Stanford.NLP.Fsharp/so_
questions.html
I am thinking I did not set up the machine correct so I am going through
all of your docs
Checking now...

**Comment by sergey-tihon** [comment]
This is the guide from another project ... and it may be broken...

Please try this one https://sergey-tihon.github.io/Stanford.NLP.NET//samples/Parser.Sample.html

**Comment by jamessdixon** [comment]
Ooops
Sorry
I'll close the item

**Comment by sergey-tihon** [comment]
Anyway, I can confirm that even this sample works in __VS2015__ on my machine

<img width="1576" alt="2017-07-18_2236" src="https://user-images.githubusercontent.com/1197905/28336212-bbebf036-6c09-11e7-8424-45b566ef91e4.png">

**Comment by jamessdixon** [comment]
I am trying it on my home machine (also VS2015)

 



 

And I am getting

> System.TypeInitializationException: The type initializer for 'edu.stanford.nlp.parser.lexparser.LexicalizedParser' threw an exception. ---> System.TypeInitializationException: The type initializer for 'edu.stanford.nlp.parser.common.ParserGrammar' threw an exception. ---> System.TypeInitializationException: The type initializer for 'edu.stanford.nlp.util.logging.Redwood' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'IKVM.Runtime, Version=8.1.5717.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58' or one of its dependencies. The system cannot find the file specified.

**Comment by jamessdixon** [comment]
Here it is from the work machine

 



 

> System.TypeInitializationException: The type initializer for 'edu.stanford.nlp.util.Timing' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'IKVM.OpenJDK.Text, Version=8.1.5717.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58' or one of its dependencies. The system cannot find the file specified.

**Comment by sergey-tihon** [comment]
Maybe small refactoring change something
```fsharp
#I "../packages/Stanford.NLP.Parser.Fsharp.0.0.13/lib/"
#r "Stanford.NLP.Parser.Fsharp.dll"
#I "../packages/Stanford.NLP.Parser.3.7.0.0/lib/"
#r "stanford-parser.dll"
#r "ejml-0.23.dll"
#I "../packages/IKVM.8.1.5717.0/lib/"
#r "IKVM.Runtime.dll"
#r "IKVM.OpenJDK.Core.dll"
#r "IKVM.OpenJDK.Text.dll"
```

**Comment by jamessdixon** [comment]
Version mismatch?

**Comment by jamessdixon** [comment]
It was NOT small

I uninstalled all of the libs and installed this:  https://www.nuget.org/packages/Stanford.NLP.Parser.Fsharp

 

And it ran

 

Thanks – I’ll close the issue
