### ISSUE TITLE
{"edu.stanford.nlp.io.RuntimeIOException: Error while loading a tagger model (probably missing model file)"}

### ISSUE THREAD

**Issue by ltdhvktqs** [sergey-tihon/Stanford.NLP.NET#71]
I download this project and try to run but it error at:

`var pipeline = new StanfordCoreNLP(props);`

Can you help me to fix it.
![2017-07-26_16-25-36](https://user-images.githubusercontent.com/30456281/28614239-46905f90-721f-11e7-989e-7147c6c857e1.png)

**Comment by sergey-tihon** [comment]
The error says that you have to model on your machine.
You should start from `build.cmd` in the project root. (it downloads several DB of zips from Stanford first)

**Comment by zahra1394** [comment]
> 
> 
> The error says that you have to model on your machine.
> You should start from `build.cmd` in the project root. (it downloads several DB of zips from Stanford first)

excuse me I couldn't understand what should be done exactly. can you describe the solution?

**Comment by sergey-tihon** [comment]
-  clone repo or download as zip archive
- open `cmd` in the root folder
- execute `build.cmd`
- wait (depends on your internet connection)

**Comment by kunalm3701** [comment]
@ltdhvktqs  did you solve your problem? I am also facing the same problem :(

**Comment by kunalm3701** [comment]
@sergey-tihon I am not able to find a build.cmd file


This is the extracted folder when I downloaded `stanford-corenlp-full-2018-10-05.zip`

![image](https://user-images.githubusercontent.com/11706889/51303252-d2f28a00-1a5a-11e9-91d8-1c60536234b6.png)

I am also facing the same problem 

![image](https://user-images.githubusercontent.com/11706889/51303326-08977300-1a5b-11e9-9d62-10f6f530ccd3.png)

I have also posted a question on SO [here](https://stackoverflow.com/questions/54230208/error-could-not-find-or-load-main-class-edu-stanford-nlp-ie-machinereading-mach)

**Comment by sergey-tihon** [comment]
`build.cmd` is the way to compile this Githug repo. - https://github.com/sergey-tihon/Stanford.NLP.NET/blob/master/build.cmd if you clone or download this.

@kunalm3701 In your case you need change current directory to `D:\stanford-corenlp-full-2018-10-05\`

P.S. http://apollo13cn.blogspot.com/2018/10/f-stanford-nlp-is-running.html

**Comment by sergey-tihon** [comment]
Close as an old issue
