### ISSUE TITLE
Training a sentiment model

### ISSUE THREAD

**Issue by tgcidsv** [sergey-tihon/Stanford.NLP.NET#72]
Hi, I am new in corenlp and i'm trying to figure out how to train a spanish sentiment model. I already have a dataset but i have no idea how to convert it to Penn Treebank (Already googled a lot, maybe bad luck). 

Additionally is there a way to train models from this solution?

I appreciate all your help.

**Comment by sergey-tihon** [comment]
Are you sure that `Spanish` models provided for [CoreNlp](https://stanfordnlp.github.io/CoreNLP/) are not suitable for sentiment analysis?

At least [online demo](http://nlp.stanford.edu:8080/sentiment/rntnDemo.html) could work with Spanish...
<img width="1027" alt="spanish" src="https://user-images.githubusercontent.com/1197905/28742766-975c0d4c-7441-11e7-946d-e2becc94d820.png">

here we have couple sample for sentiment analysis with Stanford.CoreNLP.NET (eng)
https://sergey-tihon.github.io/Stanford.NLP.NET//samples.html#Stanford-CoreNLP

**Comment by tgcidsv** [comment]
Hi Sergey, thank you for your reply. The problem with sentiment in spanish with english models is not accurate. I already have a Web Service implementation with CoreNLP .NET for sentiment analysis but i need to train a new model for spanish. I know how to do it, but i don't know how to parse the data to Treebank format.

**Comment by sergey-tihon** [comment]
Sorry, I cannot help you with this, you could try ask on SO - https://stackoverflow.com/questions/tagged/stanford-nlp or contact Stanford NLP group

**Comment by JimSEOW** [comment]
For the upcoming Stanforld-NLP version e.g. 3.9: ["Sentiment analysis is not implemented for Spanish](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/simple/SpanishDocument.java)

```
  protected Document runSentiment(Properties props) {
    throw new IllegalArgumentException("Sentiment analysis is not implemented for Spanish");
   }`
```

**Comment by sergey-tihon** [comment]
Close it for now, because it cannot be addressed directly in `.NET` version of  Stanford NLP
