### ISSUE TITLE
IOException though following the sample 

### ISSUE THREAD

**Issue by jesmin-n** [sergey-tihon/Stanford.NLP.NET#73]
I've followed the instructions to download the NuGet package, as well as the zip file with models from Stanford's page. I'm also following the C# sample by doing this: 

`var tagger = new MaxentTagger(@"/stanford-postagger-full-2016-10-31/models/wsj-0-18-left3words.tagger");`

but, I get this error in Unity: 

`IOException: Unable to open "/stanford-postagger-full-2016-10-31/models/wsj-0-18-left3words.tagger" as class path, filename or URL
edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem (System.String textFileOrUrl)
edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit (java.util.Properties config, System.String modelFileOrUrl, Boolean printLoading)
Rethrow as RuntimeIOException: Error while loading a tagger model (probably missing model file)
edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit (java.util.Properties config, System.String modelFileOrUrl, Boolean printLoading)
edu.stanford.nlp.tagger.maxent.MaxentTagger..ctor (System.String modelFile, java.util.Properties config, Boolean printLoading)
edu.stanford.nlp.tagger.maxent.MaxentTagger..ctor (System.String modelFile)
Stanford.NLP.POSTagger.CSharp.NewBehaviourScript.Start () (at Assets/NewBehaviourScript.cs:23)`

Here is what my directory looks like:

<img width="573" alt="screen shot 2017-08-03 at 10 53 05 pm" src="https://user-images.githubusercontent.com/7024778/28955915-971ce0c0-789e-11e7-8460-4dabed52b889.png">

I've been stuck on this for a few days, so any help would be very appreciated.

**Comment by sergey-tihon** [comment]
Please check that file exist on disk
```csharp
if (!File.Exist(@"/stanford-postagger-full-2016-10-31/models/wsj-0-18-left3words.tagger"))
     throw new Exception("File really does not exist")
```
This sample should work http://sergey-tihon.github.io/Stanford.NLP.NET/samples/POSTagger.Sample.html
IIRC `wsj-0-18-left3words.tagger` does not exist anymore and you should use `wsj-0-18-bidirectional-nodistsim.tagger` instead.

Note, I does not guarantee that `MaxentTagger` works correctly on Mac/Mono. I did not check it

**Comment by sergey-tihon** [comment]
Update, I did check on macOS\Mono 5.0.1 and it works, so the issue is in the path to the model file

**Comment by jesmin-n** [comment]
You're right, apparently in Unity3D you need Application.dataPath in order to get the correct path to the file. Thanks so much for helping me realize the problem!
