### ISSUE TITLE
CoreNLP version 3.8.0

### ISSUE THREAD

**Issue by JimSEOW** [sergey-tihon/Stanford.NLP.NET#74]
Please consider upgrading to CoreNLPversion 3.8.0
This will make it easier to implement these [document files.](https://github.com/stanfordnlp/CoreNLP/tree/master/src/edu/stanford/nlp/simple)

**Comment by sergey-tihon** [comment]
Released on NuGet

**Comment by sergey-tihon** [comment]
@JimSEOW Thank you for pinging, I have no idea how I miss the 3.8.0
Do not hesitate to ping me with v3.9.0

**Comment by JimSEOW** [comment]
@sergey-tihon using Stanford.NLP.NET with VS2017 seems more smooth than using VS2015. 
thanks for rapid support!
