### ISSUE TITLE
dear owner i get one problem 

### ISSUE THREAD

**Issue by leezhihui** [sergey-tihon/Stanford.NLP.NET#75]
{"java.io.IOException: Unable to open \"..\\..\\..\\..\\data\\paket-files\\nlp.stanford.edu\\stanford-segmenter-2017-06-09\\data\\ctb.gz\" as class path, filename or URL"}

when i run the demo ,i get the above error in the vs c#

**Comment by sergey-tihon** [comment]
go to the project root folder and execute `build.cmd` (it will download couple GB of trained model from Stanford site that unzip them into `data\paket-files`)

**Comment by leezhihui** [comment]
thank you ,i will do it right now.

**Comment by leezhihui** [comment]
I am doing some nlp about chinese . Does it enough after the download .
thank you
