### ISSUE TITLE
NoSuchMethodException 

### ISSUE THREAD

**Issue by ryanleecode** [sergey-tihon/Stanford.NLP.NET#78]
Im trying to run the samples but everytime I run it i get the same errors. I've installed the.NLP.CoreNLP package and I've run the build.cmd already

Exception thrown: 'edu.stanford.nlp.trees.tregex.TregexParser.LookaheadSuccess' in stanford-corenlp-3.8.0.dll
Exception thrown: 'edu.stanford.nlp.trees.tregex.TregexParser.LookaheadSuccess' in stanford-corenlp-3.8.0.dll
Exception thrown: 'ClassNotFoundException' in IKVM.Runtime.dll
Exception thrown: 'java.lang.NoClassDefFoundError' in IKVM.Runtime.dll
Exception thrown: 'java.lang.NoSuchFieldException' in IKVM.OpenJDK.Core.dll
Exception thrown: 'java.lang.NoSuchMethodException' in IKVM.OpenJDK.Core.dll
Exception thrown: 'java.lang.NoSuchMethodException' in IKVM.OpenJDK.Core.dll
...

https://i.imgur.com/8AukHx7.png

**Comment by sergey-tihon** [comment]
Could you please also print the screenshot of console window from `build.cmd`?

**Comment by drdgvhbh** [comment]
https://pastebin.com/87n3mfAR

**Comment by sergey-tihon** [comment]
The log looks slightly strange...
It should look like this - https://ci.appveyor.com/project/sergey-tihon/stanford-nlp-net

At the beginning it should restore models in `data` folder (it downloads `zip`s from internal and unzip them and extract some models from `jar`s) as a result you should get almost `6Gb` in `data` folder.

```
Downloading nlp.stanford.edu/:/software/stanford-corenlp-full-2017-06-09.zip stanford-corenlp-full-2017-06-09.zip to C:\projects\stanford-nlp-net\data\paket-files\nlp.stanford.edu\stanford-corenlp-full-2017-06-09.zip
Downloading nlp.stanford.edu/:/software/stanford-ner-2017-06-09.zip stanford-ner-2017-06-09.zip to C:\projects\stanford-nlp-net\data\paket-files\nlp.stanford.edu\stanford-ner-2017-06-09.zip
Downloading nlp.stanford.edu/:/software/stanford-parser-full-2017-06-09.zip stanford-parser-full-2017-06-09.zip to C:\projects\stanford-nlp-net\data\paket-files\nlp.stanford.edu\stanford-parser-full-2017-06-09.zip
Downloading nlp.stanford.edu/:/software/stanford-postagger-full-2017-06-09.zip stanford-postagger-full-2017-06-09.zip to C:\projects\stanford-nlp-net\data\paket-files\nlp.stanford.edu\stanford-postagger-full-2017-06-09.zip
Downloading nlp.stanford.edu/:/software/stanford-segmenter-2017-06-09.zip stanford-segmenter-2017-06-09.zip to C:\projects\stanford-nlp-net\data\paket-files\nlp.stanford.edu\stanford-segmenter-2017-06-09.zip
Downloading www.frijters.net/:/ikvmbin-8.1.5717.0.zip ikvmbin-8.1.5717.0.zip to C:\projects\stanford-nlp-net\data\paket-files\www.frijters.net\ikvmbin-8.1.5717.0.zip
```

Also I see that your log ends around here https://ci.appveyor.com/project/sergey-tihon/stanford-nlp-net/build/0.0.1.99#L1243 so your log does not have test execution results, only some fst log lines from expecto
