### ISSUE TITLE
There is an warning message

### ISSUE THREAD

**Issue by hohuynh** [sergey-tihon/Stanford.NLP.NET#79]
Below is my code as your example, it ran without error but there is a warning message like image in attachment. I installed stanford-corenlp-3.8.0 from nuget. Could you let me know what issue here ?

`var jarRoot = @"..\..\..\StanfordNLP\stanford-english-corenlp-models";

            // Annotation pipeline configuration
            var props = new Properties();
            //props.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner,parse,dcoref"); 
            props.setProperty("ner.useSUTime", "0");

            // We should change current directory, so StanfordCoreNLP could find all the model files automatically
            var curDir = Environment.CurrentDirectory;
            Directory.SetCurrentDirectory(jarRoot);
            var pipeline = new StanfordCoreNLP(props);
            Directory.SetCurrentDirectory(curDir);

            // Annotation
            var annotation = new Annotation(sentence);
            pipeline.annotate(annotation); `

![image](https://user-images.githubusercontent.com/12832409/32700268-31748f06-c7f5-11e7-90b2-be6beedd0f8f.png)

Thanks,

**Comment by sergey-tihon** [comment]
This is known warnings - sorry. I do not know yet a way to fix or work around them.

I guess that the reason is that StanfordNLP group does not ship `slf4j` in zip packages, so we do not recompile them and .NET runtime could load classes at runtime.
