### ISSUE TITLE
Sentiment analysis train! help me,please!

### ISSUE THREAD

**Issue by wzjjia** [sergey-tihon/Stanford.NLP.NET#86]
How does the Sentiment analysis  function train me to provide a sentence like, "I'm happy today" and I'm going to train him to be positive

**Comment by sergey-tihon** [comment]
Sorry, but I am not aware of any way to train your own model.

As I understand, the shipped model is trained using `Sentiment Treebank`
https://nlp.stanford.edu/sentiment/treebank.html
So you can your cases there and next model version should be better.

You also may want to search issues on original repo https://github.com/stanfordnlp/CoreNLP or questions on SO https://stackoverflow.com/questions/tagged/stanford-nlp

Seems that there is a way to do this...
- https://github.com/stanfordnlp/CoreNLP/issues/32
- https://github.com/stanfordnlp/CoreNLP/issues/553

**Comment by wzjjia** [comment]
"If you sometimes like to go to the movies  to have fun Wasabi is a good place to start."
How can I convert the above statement to the following format？
(3 (3 (2 If) (3 (2 you) (3 (2 sometimes) (2 (2 like) (3 (2 to) (3 (3 (2 go) (2 (2 to) (2 (2 the) (2 movies)))) (3 (2 to) (3 (2 have) (4 fun))))))))) (2 (2 ,) (2 (2 Wasabi) (3 (3 (2 is) (2 (2 a) (2 (3 good) (2 (2 place) (2 (2 to) (2 start)))))) (2 .)))))

**Comment by cheungtitus** [comment]
@wzjjia I'm new to this as well but it appears BuildBinarizedDataset is the one to use.
https://github.com/stanfordnlp/CoreNLP/issues/296
https://github.com/stanfordnlp/CoreNLP/issues/32#issuecomment-61037436
https://www.kaggle.com/c/sentiment-analysis-on-movie-reviews/discussion/12304

What is not clear is how do you break down each sentence into its phrases and then assign sentiment scores for them.

For example why for this sentence.
`Today is not a good day.`

How do we know it has the following phrases.
```
good
good day
a good day
```

**Comment by wzjjia** [comment]
Here's the problem
How do we know it has the following phrases.
good
good day
a good day

**Comment by bond-** [comment]
Wow seriously?? no one responded to this. That just shows the amount of support CoreNLP has.

**Comment by sergey-tihon** [comment]
Sorry, this is the wrong repo for such questions
Please ask on StackOverflow or open new issue in official repo https://github.com/stanfordnlp/CoreNLP

**Comment by bond-** [comment]
Opps sorry didn't look at the repo name
