### ISSUE TITLE
Sentiment analysis train! help me,please! 

### ISSUE THREAD

**Issue by wzjjia** [sergey-tihon/Stanford.NLP.NET#87]
"If you sometimes like to go to the movies to have fun Wasabi is a good place to start."

How can I convert the above statement to the following format？

(3 (3 (2 If) (3 (2 you) (3 (2 sometimes) (2 (2 like) (3 (2 to) (3 (3 (2 go) (2 (2 to) (2 (2 the) (2 movies)))) (3 (2 to) (3 (2 have) (4 fun))))))))) (2 (2 ,) (2 (2 Wasabi) (3 (3 (2 is) (2 (2 a) (2 (3 good) (2 (2 place) (2 (2 to) (2 start)))))) (2 .)))))

**Comment by wzjjia** [comment]
How is the code implemented?

**Comment by sergey-tihon** [comment]
Probably like this - https://github.com/evelinag/SentimentAnalysisDemo/blob/master/code/sentiment.fsx#L52

But note, that is repo is for `Stanford.NLP.NET` - the .net binary port of `CoreNLP`.
There is no any NLP algorithm implemented here.
