### ISSUE TITLE
Stanford NLP stuck when using large text

### ISSUE THREAD

**Issue by Anupam750** [sergey-tihon/Stanford.NLP.NET#90]
Stanford NLP stuck when using large text for segmentor. Please check it.

**Comment by sergey-tihon** [comment]
Do you mean `Stanford.NLP.Segmenter`?

**Comment by Anupam750** [comment]
Yes Stanford.NLP.Segmenter

**Comment by Anupam750** [comment]
above code is giving compile time error as this code is in java so do we have any code in C#?

**Comment by sergey-tihon** [comment]
@Anupam750 not yet, sorry. But it should not be hard to convert Java sample to C# sample

**Comment by sergey-tihon** [comment]
Cannot help you without sample code and stack trace.
You can try C# sample from the same SO answer
```csharp
public class NlpDemo
{
    public static readonly TokenizerFactory TokenizerFactory = PTBTokenizer.factory(new CoreLabelTokenFactory(),
                "normalizeParentheses=false,normalizeOtherBrackets=false,invertible=true");

    public void ParseFile(string fileName)
    {
        using (var stream = File.OpenRead(fileName))
        {
            SplitSentences(stream);
        }
    }

    public void SplitSentences(Stream stream)
    {            
        var preProcessor = new DocumentPreprocessor(new UTF8Reader(new InputStreamWrapper(stream)));
        preProcessor.setTokenizerFactory(TokenizerFactory);

        foreach (java.util.List sentence in preProcessor)
        {
            ProcessSentence(sentence);
        }            
    }

    // print the sentence with original spaces and punctuation.
    public void ProcessSentence(java.util.List sentence)
    {
        System.Console.WriteLine(edu.stanford.nlp.util.StringUtils.joinWithOriginalWhiteSpace(sentence));
    }
}
```

or as alternative use CoreNLP package and extract list of sentences from annotation
https://github.com/sergey-tihon/Stanford.NLP.NET/blob/master/samples/Stanford.NLP.CoreNLP.CSharp/StanfordCoreNlpClient.cs#L35-L36

but I have no idea how large your text is.

**Comment by Anupam750** [comment]
my text is around 300 pages pdf file

**Comment by abhi18av** [comment]
Hello everyone,

If this issue is resolved could you please update here the solution and
explain how you resolved it ?

**Comment by sergey-tihon** [comment]
Close as an old issue
