### ISSUE TITLE
License

### ISSUE THREAD

**Issue by NeomMob** [sergey-tihon/Stanford.NLP.NET#93]
I've seen that StanfordNLP has recently moved to an Apache License, Version 2.0.

Are you planning to do the same for Stanford.NLP.NET ?

I

**Comment by sergey-tihon** [comment]
@NeomMob could you please point me to info  about Apache license.

I see that official repo is under GNU license - https://github.com/stanfordnlp/CoreNLP
and on the site -https://nlp.stanford.edu/software/ 

> These software distributions are open source, licensed under the GNU General Public License (v3 or later for Stanford CoreNLP; v2 or later for the other releases). Note that this is the full GPL, which allows many free uses, but does not allow its incorporation  ...

**Comment by NeomMob** [comment]
I was wrong, I was talling about https://github.com/stanfordnlp/stanfordnlp which recently moved to Apache. Wondering why we had a such change and possible coming changes to otehr libs.
