### ISSUE TITLE
In connecting to NLP service,While using sentences annotation getting  null value 

### ISSUE THREAD

**Issue by jgazelle** [sergey-tihon/Stanford.NLP.NET#94]
I used the code from the below link
https://sergey-tihon.github.io/Stanford.NLP.NET//samples/CoreNLP.Server.html
Here sentences returns null 
var sentences = document.get(sentencesAnnotationClass) as java.util.AbstractList;

**Comment by jgazelle** [comment]
If i use 'tokenize' and ssplit it is not returning null.When I add 'pos' then sentences above is giving null

**Comment by sergey-tihon** [comment]
Sample is fixed and updated in docs

```sharp
        var sentencesAnnotationClass = GetAnnotationClass<CoreAnnotations.SentencesAnnotation>();
        var sentences = sentencesAnnotationClass.getClasses().Select(document.get).ToList();
```
